/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gtroup (void)
{
  GtkWidget *gtroup;
  GtkWidget *fixed11;
  GtkWidget *button_ajtrp;
  GtkWidget *alignment32;
  GtkWidget *hbox32;
  GtkWidget *image43;
  GtkWidget *label76;
  GtkWidget *button_afftrp;
  GtkWidget *alignment31;
  GtkWidget *hbox31;
  GtkWidget *image42;
  GtkWidget *label75;
  GtkWidget *button_mdftrp;
  GtkWidget *alignment33;
  GtkWidget *hbox33;
  GtkWidget *image44;
  GtkWidget *label77;
  GtkWidget *button_supptrp;
  GtkWidget *alignment34;
  GtkWidget *hbox34;
  GtkWidget *image45;
  GtkWidget *label78;
  GtkWidget *treeview_ltrp;
  GtkWidget *button_retgtrp;
  GtkWidget *alignment35;
  GtkWidget *hbox35;
  GtkWidget *image46;
  GtkWidget *label79;
  GtkWidget *button_kdgrch;
  GtkWidget *alignment77;
  GtkWidget *hbox77;
  GtkWidget *image103;
  GtkWidget *label188;

  gtroup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gtroup, 750, 430);
  gtk_window_set_title (GTK_WINDOW (gtroup), _("Gestion des troupeaux "));

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (gtroup), fixed11);

  button_ajtrp = gtk_button_new ();
  gtk_widget_show (button_ajtrp);
  gtk_fixed_put (GTK_FIXED (fixed11), button_ajtrp, 168, 400);
  gtk_widget_set_size_request (button_ajtrp, 105, 29);

  alignment32 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment32);
  gtk_container_add (GTK_CONTAINER (button_ajtrp), alignment32);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment32), hbox32);

  image43 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image43);
  gtk_box_pack_start (GTK_BOX (hbox32), image43, FALSE, FALSE, 0);

  label76 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label76);
  gtk_box_pack_start (GTK_BOX (hbox32), label76, FALSE, FALSE, 0);

  button_afftrp = gtk_button_new ();
  gtk_widget_show (button_afftrp);
  gtk_fixed_put (GTK_FIXED (fixed11), button_afftrp, 8, 400);
  gtk_widget_set_size_request (button_afftrp, 105, 29);

  alignment31 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment31);
  gtk_container_add (GTK_CONTAINER (button_afftrp), alignment31);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment31), hbox31);

  image42 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image42);
  gtk_box_pack_start (GTK_BOX (hbox31), image42, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox31), label75, FALSE, FALSE, 0);

  button_mdftrp = gtk_button_new ();
  gtk_widget_show (button_mdftrp);
  gtk_fixed_put (GTK_FIXED (fixed11), button_mdftrp, 328, 400);
  gtk_widget_set_size_request (button_mdftrp, 105, 29);

  alignment33 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment33);
  gtk_container_add (GTK_CONTAINER (button_mdftrp), alignment33);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment33), hbox33);

  image44 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox33), image44, FALSE, FALSE, 0);

  label77 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label77);
  gtk_box_pack_start (GTK_BOX (hbox33), label77, FALSE, FALSE, 0);

  button_supptrp = gtk_button_new ();
  gtk_widget_show (button_supptrp);
  gtk_fixed_put (GTK_FIXED (fixed11), button_supptrp, 488, 400);
  gtk_widget_set_size_request (button_supptrp, 105, 29);

  alignment34 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment34);
  gtk_container_add (GTK_CONTAINER (button_supptrp), alignment34);

  hbox34 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox34);
  gtk_container_add (GTK_CONTAINER (alignment34), hbox34);

  image45 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox34), image45, FALSE, FALSE, 0);

  label78 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label78);
  gtk_box_pack_start (GTK_BOX (hbox34), label78, FALSE, FALSE, 0);

  treeview_ltrp = gtk_tree_view_new ();
  gtk_widget_show (treeview_ltrp);
  gtk_fixed_put (GTK_FIXED (fixed11), treeview_ltrp, 0, 120);
  gtk_widget_set_size_request (treeview_ltrp, 750, 216);

  button_retgtrp = gtk_button_new ();
  gtk_widget_show (button_retgtrp);
  gtk_fixed_put (GTK_FIXED (fixed11), button_retgtrp, 32, 16);
  gtk_widget_set_size_request (button_retgtrp, 85, 29);

  alignment35 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment35);
  gtk_container_add (GTK_CONTAINER (button_retgtrp), alignment35);

  hbox35 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox35);
  gtk_container_add (GTK_CONTAINER (alignment35), hbox35);

  image46 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_box_pack_start (GTK_BOX (hbox35), image46, FALSE, FALSE, 0);

  label79 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label79);
  gtk_box_pack_start (GTK_BOX (hbox35), label79, FALSE, FALSE, 0);

  button_kdgrch = gtk_button_new ();
  gtk_widget_show (button_kdgrch);
  gtk_fixed_put (GTK_FIXED (fixed11), button_kdgrch, 624, 400);
  gtk_widget_set_size_request (button_kdgrch, 105, 29);

  alignment77 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment77);
  gtk_container_add (GTK_CONTAINER (button_kdgrch), alignment77);

  hbox77 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox77);
  gtk_container_add (GTK_CONTAINER (alignment77), hbox77);

  image103 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image103);
  gtk_box_pack_start (GTK_BOX (hbox77), image103, FALSE, FALSE, 0);

  label188 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label188);
  gtk_box_pack_start (GTK_BOX (hbox77), label188, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_ajtrp, "clicked",
                    G_CALLBACK (on_button_ajtrp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_afftrp, "clicked",
                    G_CALLBACK (on_button_afftrp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_mdftrp, "clicked",
                    G_CALLBACK (on_button_mdftrp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supptrp, "clicked",
                    G_CALLBACK (on_button_supptrp_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview_ltrp, "row_activated",
                    G_CALLBACK (on_treeview_ltrp_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_retgtrp, "clicked",
                    G_CALLBACK (on_button_retgtrp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_kdgrch, "clicked",
                    G_CALLBACK (on_button_kdgrch_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gtroup, gtroup, "gtroup");
  GLADE_HOOKUP_OBJECT (gtroup, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (gtroup, button_ajtrp, "button_ajtrp");
  GLADE_HOOKUP_OBJECT (gtroup, alignment32, "alignment32");
  GLADE_HOOKUP_OBJECT (gtroup, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (gtroup, image43, "image43");
  GLADE_HOOKUP_OBJECT (gtroup, label76, "label76");
  GLADE_HOOKUP_OBJECT (gtroup, button_afftrp, "button_afftrp");
  GLADE_HOOKUP_OBJECT (gtroup, alignment31, "alignment31");
  GLADE_HOOKUP_OBJECT (gtroup, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (gtroup, image42, "image42");
  GLADE_HOOKUP_OBJECT (gtroup, label75, "label75");
  GLADE_HOOKUP_OBJECT (gtroup, button_mdftrp, "button_mdftrp");
  GLADE_HOOKUP_OBJECT (gtroup, alignment33, "alignment33");
  GLADE_HOOKUP_OBJECT (gtroup, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (gtroup, image44, "image44");
  GLADE_HOOKUP_OBJECT (gtroup, label77, "label77");
  GLADE_HOOKUP_OBJECT (gtroup, button_supptrp, "button_supptrp");
  GLADE_HOOKUP_OBJECT (gtroup, alignment34, "alignment34");
  GLADE_HOOKUP_OBJECT (gtroup, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (gtroup, image45, "image45");
  GLADE_HOOKUP_OBJECT (gtroup, label78, "label78");
  GLADE_HOOKUP_OBJECT (gtroup, treeview_ltrp, "treeview_ltrp");
  GLADE_HOOKUP_OBJECT (gtroup, button_retgtrp, "button_retgtrp");
  GLADE_HOOKUP_OBJECT (gtroup, alignment35, "alignment35");
  GLADE_HOOKUP_OBJECT (gtroup, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (gtroup, image46, "image46");
  GLADE_HOOKUP_OBJECT (gtroup, label79, "label79");
  GLADE_HOOKUP_OBJECT (gtroup, button_kdgrch, "button_kdgrch");
  GLADE_HOOKUP_OBJECT (gtroup, alignment77, "alignment77");
  GLADE_HOOKUP_OBJECT (gtroup, hbox77, "hbox77");
  GLADE_HOOKUP_OBJECT (gtroup, image103, "image103");
  GLADE_HOOKUP_OBJECT (gtroup, label188, "label188");

  return gtroup;
}

GtkWidget*
create_ajttroup (void)
{
  GtkWidget *ajttroup;
  GtkWidget *fixed12;
  GtkWidget *label_kdidajt;
  GtkWidget *entry_kdidajt;
  GtkWidget *label_kdtpajt;
  GtkWidget *label_kdsexeajt;
  GtkWidget *radiobutton_kdmajt;
  GSList *radiobutton_kdmajt_group = NULL;
  GtkWidget *radiobutton_kdfajt;
  GtkObject *spinbutton_kdjdnajt_adj;
  GtkWidget *spinbutton_kdjdnajt;
  GtkObject *spinbutton_kdmdnajt_adj;
  GtkWidget *spinbutton_kdmdnajt;
  GtkObject *spinbutton_kdadnajt_adj;
  GtkWidget *spinbutton_kdadnajt;
  GtkWidget *label_kddnajt;
  GtkObject *spinbutton_kdjdvajt_adj;
  GtkWidget *spinbutton_kdjdvajt;
  GtkObject *spinbutton_kdmdvajt_adj;
  GtkWidget *spinbutton_kdmdvajt;
  GtkObject *spinbutton_kdadvajt_adj;
  GtkWidget *spinbutton_kdadvajt;
  GtkWidget *button_kdanlajt;
  GtkWidget *alignment38;
  GtkWidget *hbox38;
  GtkWidget *image50;
  GtkWidget *label88;
  GtkWidget *button_kdcnfajt;
  GtkWidget *alignment37;
  GtkWidget *hbox37;
  GtkWidget *image49;
  GtkWidget *label87;
  GtkWidget *combobox_kdtpaj;
  GtkWidget *label_kdesajt;
  GtkWidget *combobox_kdesaj;
  GtkWidget *label_kddvajt;

  ajttroup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajttroup, 620, 430);
  gtk_window_set_title (GTK_WINDOW (ajttroup), _("Ajout troupeaux"));

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_container_add (GTK_CONTAINER (ajttroup), fixed12);

  label_kdidajt = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label_kdidajt);
  gtk_fixed_put (GTK_FIXED (fixed12), label_kdidajt, 184, 8);
  gtk_widget_set_size_request (label_kdidajt, 97, 33);

  entry_kdidajt = gtk_entry_new ();
  gtk_widget_show (entry_kdidajt);
  gtk_fixed_put (GTK_FIXED (fixed12), entry_kdidajt, 312, 16);
  gtk_widget_set_size_request (entry_kdidajt, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_kdidajt), 8226);

  label_kdtpajt = gtk_label_new (_("Type :"));
  gtk_widget_show (label_kdtpajt);
  gtk_fixed_put (GTK_FIXED (fixed12), label_kdtpajt, 216, 48);
  gtk_widget_set_size_request (label_kdtpajt, 73, 25);

  label_kdsexeajt = gtk_label_new (_("Genre :"));
  gtk_widget_show (label_kdsexeajt);
  gtk_fixed_put (GTK_FIXED (fixed12), label_kdsexeajt, 224, 88);
  gtk_widget_set_size_request (label_kdsexeajt, 57, 33);

  radiobutton_kdmajt = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobutton_kdmajt);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton_kdmajt, 312, 96);
  gtk_widget_set_size_request (radiobutton_kdmajt, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_kdmajt), radiobutton_kdmajt_group);
  radiobutton_kdmajt_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_kdmajt));

  radiobutton_kdfajt = gtk_radio_button_new_with_mnemonic (NULL, _("Femelle"));
  gtk_widget_show (radiobutton_kdfajt);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton_kdfajt, 400, 96);
  gtk_widget_set_size_request (radiobutton_kdfajt, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_kdfajt), radiobutton_kdmajt_group);
  radiobutton_kdmajt_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_kdfajt));

  spinbutton_kdjdnajt_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_kdjdnajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdjdnajt_adj), 1, 0);
  gtk_widget_show (spinbutton_kdjdnajt);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_kdjdnajt, 312, 128);
  gtk_widget_set_size_request (spinbutton_kdjdnajt, 60, 27);

  spinbutton_kdmdnajt_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_kdmdnajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdmdnajt_adj), 1, 0);
  gtk_widget_show (spinbutton_kdmdnajt);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_kdmdnajt, 392, 128);
  gtk_widget_set_size_request (spinbutton_kdmdnajt, 60, 27);

  spinbutton_kdadnajt_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_kdadnajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdadnajt_adj), 1, 0);
  gtk_widget_show (spinbutton_kdadnajt);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_kdadnajt, 472, 128);
  gtk_widget_set_size_request (spinbutton_kdadnajt, 60, 27);

  label_kddnajt = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label_kddnajt);
  gtk_fixed_put (GTK_FIXED (fixed12), label_kddnajt, 136, 128);
  gtk_widget_set_size_request (label_kddnajt, 144, 33);

  spinbutton_kdjdvajt_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_kdjdvajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdjdvajt_adj), 1, 0);
  gtk_widget_show (spinbutton_kdjdvajt);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_kdjdvajt, 312, 208);
  gtk_widget_set_size_request (spinbutton_kdjdvajt, 60, 27);

  spinbutton_kdmdvajt_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_kdmdvajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdmdvajt_adj), 1, 0);
  gtk_widget_show (spinbutton_kdmdvajt);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_kdmdvajt, 392, 208);
  gtk_widget_set_size_request (spinbutton_kdmdvajt, 60, 27);

  spinbutton_kdadvajt_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_kdadvajt = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdadvajt_adj), 1, 0);
  gtk_widget_show (spinbutton_kdadvajt);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton_kdadvajt, 472, 208);
  gtk_widget_set_size_request (spinbutton_kdadvajt, 60, 27);

  button_kdanlajt = gtk_button_new ();
  gtk_widget_show (button_kdanlajt);
  gtk_fixed_put (GTK_FIXED (fixed12), button_kdanlajt, 400, 400);
  gtk_widget_set_size_request (button_kdanlajt, 105, 29);

  alignment38 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (button_kdanlajt), alignment38);

  hbox38 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox38);
  gtk_container_add (GTK_CONTAINER (alignment38), hbox38);

  image50 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image50);
  gtk_box_pack_start (GTK_BOX (hbox38), image50, FALSE, FALSE, 0);

  label88 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label88);
  gtk_box_pack_start (GTK_BOX (hbox38), label88, FALSE, FALSE, 0);

  button_kdcnfajt = gtk_button_new ();
  gtk_widget_show (button_kdcnfajt);
  gtk_fixed_put (GTK_FIXED (fixed12), button_kdcnfajt, 250, 400);
  gtk_widget_set_size_request (button_kdcnfajt, 105, 29);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (button_kdcnfajt), alignment37);

  hbox37 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox37);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox37);

  image49 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image49);
  gtk_box_pack_start (GTK_BOX (hbox37), image49, FALSE, FALSE, 0);

  label87 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label87);
  gtk_box_pack_start (GTK_BOX (hbox37), label87, FALSE, FALSE, 0);

  combobox_kdtpaj = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_kdtpaj);
  gtk_fixed_put (GTK_FIXED (fixed12), combobox_kdtpaj, 312, 56);
  gtk_widget_set_size_request (combobox_kdtpaj, 160, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdtpaj), _("Brebi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdtpaj), _("Veau"));

  label_kdesajt = gtk_label_new (_("Etat de l'animal :"));
  gtk_widget_show (label_kdesajt);
  gtk_fixed_put (GTK_FIXED (fixed12), label_kdesajt, 160, 160);
  gtk_widget_set_size_request (label_kdesajt, 121, 41);

  combobox_kdesaj = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_kdesaj);
  gtk_fixed_put (GTK_FIXED (fixed12), combobox_kdesaj, 312, 168);
  gtk_widget_set_size_request (combobox_kdesaj, 160, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdesaj), _("Vivant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdesaj), _("Malade"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdesaj), _("D\303\251c\303\250s"));

  label_kddvajt = gtk_label_new (_("Date d'examen m\303\251dical:"));
  gtk_widget_show (label_kddvajt);
  gtk_fixed_put (GTK_FIXED (fixed12), label_kddvajt, 104, 200);
  gtk_widget_set_size_request (label_kddvajt, 176, 40);

  g_signal_connect ((gpointer) radiobutton_kdmajt, "toggled",
                    G_CALLBACK (on_radiobutton_kdmajt_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_kdfajt, "toggled",
                    G_CALLBACK (on_radiobutton_kdfajt_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_kdanlajt, "clicked",
                    G_CALLBACK (on_button_kdanlajt_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_kdcnfajt, "clicked",
                    G_CALLBACK (on_button_kdcnfajt_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajttroup, ajttroup, "ajttroup");
  GLADE_HOOKUP_OBJECT (ajttroup, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (ajttroup, label_kdidajt, "label_kdidajt");
  GLADE_HOOKUP_OBJECT (ajttroup, entry_kdidajt, "entry_kdidajt");
  GLADE_HOOKUP_OBJECT (ajttroup, label_kdtpajt, "label_kdtpajt");
  GLADE_HOOKUP_OBJECT (ajttroup, label_kdsexeajt, "label_kdsexeajt");
  GLADE_HOOKUP_OBJECT (ajttroup, radiobutton_kdmajt, "radiobutton_kdmajt");
  GLADE_HOOKUP_OBJECT (ajttroup, radiobutton_kdfajt, "radiobutton_kdfajt");
  GLADE_HOOKUP_OBJECT (ajttroup, spinbutton_kdjdnajt, "spinbutton_kdjdnajt");
  GLADE_HOOKUP_OBJECT (ajttroup, spinbutton_kdmdnajt, "spinbutton_kdmdnajt");
  GLADE_HOOKUP_OBJECT (ajttroup, spinbutton_kdadnajt, "spinbutton_kdadnajt");
  GLADE_HOOKUP_OBJECT (ajttroup, label_kddnajt, "label_kddnajt");
  GLADE_HOOKUP_OBJECT (ajttroup, spinbutton_kdjdvajt, "spinbutton_kdjdvajt");
  GLADE_HOOKUP_OBJECT (ajttroup, spinbutton_kdmdvajt, "spinbutton_kdmdvajt");
  GLADE_HOOKUP_OBJECT (ajttroup, spinbutton_kdadvajt, "spinbutton_kdadvajt");
  GLADE_HOOKUP_OBJECT (ajttroup, button_kdanlajt, "button_kdanlajt");
  GLADE_HOOKUP_OBJECT (ajttroup, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (ajttroup, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (ajttroup, image50, "image50");
  GLADE_HOOKUP_OBJECT (ajttroup, label88, "label88");
  GLADE_HOOKUP_OBJECT (ajttroup, button_kdcnfajt, "button_kdcnfajt");
  GLADE_HOOKUP_OBJECT (ajttroup, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (ajttroup, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (ajttroup, image49, "image49");
  GLADE_HOOKUP_OBJECT (ajttroup, label87, "label87");
  GLADE_HOOKUP_OBJECT (ajttroup, combobox_kdtpaj, "combobox_kdtpaj");
  GLADE_HOOKUP_OBJECT (ajttroup, label_kdesajt, "label_kdesajt");
  GLADE_HOOKUP_OBJECT (ajttroup, combobox_kdesaj, "combobox_kdesaj");
  GLADE_HOOKUP_OBJECT (ajttroup, label_kddvajt, "label_kddvajt");

  return ajttroup;
}

GtkWidget*
create_mdftroup (void)
{
  GtkWidget *mdftroup;
  GtkWidget *fixed13;
  GtkWidget *entry_kdidmdf;
  GtkWidget *label_kdidmdf;
  GtkWidget *label_kdtpmdf;
  GtkWidget *label_kdsexemdf;
  GtkWidget *radiobutton_kdmmdf;
  GSList *radiobutton_kdmmdf_group = NULL;
  GtkWidget *radiobutton_kdfmdf;
  GtkWidget *label_kddnmdf;
  GtkObject *spinbutton_kdjdnmdf_adj;
  GtkWidget *spinbutton_kdjdnmdf;
  GtkObject *spinbutton_kdmdnmdf_adj;
  GtkWidget *spinbutton_kdmdnmdf;
  GtkObject *spinbutton_kdadnmdf_adj;
  GtkWidget *spinbutton_kdadnmdf;
  GtkObject *spinbutton_kdjdvmdf_adj;
  GtkWidget *spinbutton_kdjdvmdf;
  GtkObject *spinbutton_kdmdvmdf_adj;
  GtkWidget *spinbutton_kdmdvmdf;
  GtkObject *spinbutton_kdadvmdf_adj;
  GtkWidget *spinbutton_kdadvmdf;
  GtkWidget *button_kdanlmdf;
  GtkWidget *alignment40;
  GtkWidget *hbox40;
  GtkWidget *image53;
  GtkWidget *label96;
  GtkWidget *button_kdcnfmdf;
  GtkWidget *alignment39;
  GtkWidget *hbox39;
  GtkWidget *image52;
  GtkWidget *label95;
  GtkWidget *combobox_kdtpmdf;
  GtkWidget *label_kdesmdf;
  GtkWidget *combobox_kdesmdf;
  GtkWidget *label_kddvmdf;

  mdftroup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (mdftroup, 620, 430);
  gtk_window_set_title (GTK_WINDOW (mdftroup), _("Modifier informations troupeaux "));

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_container_add (GTK_CONTAINER (mdftroup), fixed13);

  entry_kdidmdf = gtk_entry_new ();
  gtk_widget_show (entry_kdidmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), entry_kdidmdf, 336, 24);
  gtk_widget_set_size_request (entry_kdidmdf, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_kdidmdf), 8226);

  label_kdidmdf = gtk_label_new (_("Identifiant :"));
  gtk_widget_show (label_kdidmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), label_kdidmdf, 200, 24);
  gtk_widget_set_size_request (label_kdidmdf, 89, 25);

  label_kdtpmdf = gtk_label_new (_("Type :"));
  gtk_widget_show (label_kdtpmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), label_kdtpmdf, 224, 64);
  gtk_widget_set_size_request (label_kdtpmdf, 81, 25);

  label_kdsexemdf = gtk_label_new (_("Sexe :"));
  gtk_widget_show (label_kdsexemdf);
  gtk_fixed_put (GTK_FIXED (fixed13), label_kdsexemdf, 232, 104);
  gtk_widget_set_size_request (label_kdsexemdf, 65, 25);

  radiobutton_kdmmdf = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobutton_kdmmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton_kdmmdf, 336, 104);
  gtk_widget_set_size_request (radiobutton_kdmmdf, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_kdmmdf), radiobutton_kdmmdf_group);
  radiobutton_kdmmdf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_kdmmdf));

  radiobutton_kdfmdf = gtk_radio_button_new_with_mnemonic (NULL, _("Femelle"));
  gtk_widget_show (radiobutton_kdfmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), radiobutton_kdfmdf, 424, 104);
  gtk_widget_set_size_request (radiobutton_kdfmdf, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_kdfmdf), radiobutton_kdmmdf_group);
  radiobutton_kdmmdf_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_kdfmdf));

  label_kddnmdf = gtk_label_new (_("Date de naissance :"));
  gtk_widget_show (label_kddnmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), label_kddnmdf, 144, 136);
  gtk_widget_set_size_request (label_kddnmdf, 152, 33);

  spinbutton_kdjdnmdf_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_kdjdnmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdjdnmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_kdjdnmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton_kdjdnmdf, 336, 136);
  gtk_widget_set_size_request (spinbutton_kdjdnmdf, 60, 27);

  spinbutton_kdmdnmdf_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_kdmdnmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdmdnmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_kdmdnmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton_kdmdnmdf, 416, 136);
  gtk_widget_set_size_request (spinbutton_kdmdnmdf, 60, 27);

  spinbutton_kdadnmdf_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_kdadnmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdadnmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_kdadnmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton_kdadnmdf, 496, 136);
  gtk_widget_set_size_request (spinbutton_kdadnmdf, 60, 27);

  spinbutton_kdjdvmdf_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_kdjdvmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdjdvmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_kdjdvmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton_kdjdvmdf, 336, 216);
  gtk_widget_set_size_request (spinbutton_kdjdvmdf, 60, 27);

  spinbutton_kdmdvmdf_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton_kdmdvmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdmdvmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_kdmdvmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton_kdmdvmdf, 416, 216);
  gtk_widget_set_size_request (spinbutton_kdmdvmdf, 60, 27);

  spinbutton_kdadvmdf_adj = gtk_adjustment_new (2020, 1900, 2100, 1, 10, 10);
  spinbutton_kdadvmdf = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_kdadvmdf_adj), 1, 0);
  gtk_widget_show (spinbutton_kdadvmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), spinbutton_kdadvmdf, 496, 216);
  gtk_widget_set_size_request (spinbutton_kdadvmdf, 60, 27);

  button_kdanlmdf = gtk_button_new ();
  gtk_widget_show (button_kdanlmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), button_kdanlmdf, 400, 400);
  gtk_widget_set_size_request (button_kdanlmdf, 105, 29);

  alignment40 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment40);
  gtk_container_add (GTK_CONTAINER (button_kdanlmdf), alignment40);

  hbox40 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox40);
  gtk_container_add (GTK_CONTAINER (alignment40), hbox40);

  image53 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox40), image53, FALSE, FALSE, 0);

  label96 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox40), label96, FALSE, FALSE, 0);

  button_kdcnfmdf = gtk_button_new ();
  gtk_widget_show (button_kdcnfmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), button_kdcnfmdf, 250, 400);
  gtk_widget_set_size_request (button_kdcnfmdf, 105, 29);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (button_kdcnfmdf), alignment39);

  hbox39 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox39);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox39);

  image52 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image52);
  gtk_box_pack_start (GTK_BOX (hbox39), image52, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox39), label95, FALSE, FALSE, 0);

  combobox_kdtpmdf = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_kdtpmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), combobox_kdtpmdf, 336, 64);
  gtk_widget_set_size_request (combobox_kdtpmdf, 160, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdtpmdf), _("Brebi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdtpmdf), _("Veau"));

  label_kdesmdf = gtk_label_new (_("Etat de l'animal :"));
  gtk_widget_show (label_kdesmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), label_kdesmdf, 168, 176);
  gtk_widget_set_size_request (label_kdesmdf, 128, 33);

  combobox_kdesmdf = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_kdesmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), combobox_kdesmdf, 336, 176);
  gtk_widget_set_size_request (combobox_kdesmdf, 160, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdesmdf), _("Vivant"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdesmdf), _("Malade"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_kdesmdf), _("D\303\251c\303\250s"));

  label_kddvmdf = gtk_label_new (_("Date d'examen m\303\251dical:"));
  gtk_widget_show (label_kddvmdf);
  gtk_fixed_put (GTK_FIXED (fixed13), label_kddvmdf, 120, 208);
  gtk_widget_set_size_request (label_kddvmdf, 176, 40);

  g_signal_connect ((gpointer) radiobutton_kdmmdf, "toggled",
                    G_CALLBACK (on_radiobutton_kdmmdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_kdfmdf, "toggled",
                    G_CALLBACK (on_radiobutton_kdfmdf_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_kdanlmdf, "clicked",
                    G_CALLBACK (on_button_kdanlmdf_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_kdcnfmdf, "clicked",
                    G_CALLBACK (on_button_kdcnfmdf_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mdftroup, mdftroup, "mdftroup");
  GLADE_HOOKUP_OBJECT (mdftroup, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (mdftroup, entry_kdidmdf, "entry_kdidmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, label_kdidmdf, "label_kdidmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, label_kdtpmdf, "label_kdtpmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, label_kdsexemdf, "label_kdsexemdf");
  GLADE_HOOKUP_OBJECT (mdftroup, radiobutton_kdmmdf, "radiobutton_kdmmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, radiobutton_kdfmdf, "radiobutton_kdfmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, label_kddnmdf, "label_kddnmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, spinbutton_kdjdnmdf, "spinbutton_kdjdnmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, spinbutton_kdmdnmdf, "spinbutton_kdmdnmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, spinbutton_kdadnmdf, "spinbutton_kdadnmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, spinbutton_kdjdvmdf, "spinbutton_kdjdvmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, spinbutton_kdmdvmdf, "spinbutton_kdmdvmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, spinbutton_kdadvmdf, "spinbutton_kdadvmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, button_kdanlmdf, "button_kdanlmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (mdftroup, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (mdftroup, image53, "image53");
  GLADE_HOOKUP_OBJECT (mdftroup, label96, "label96");
  GLADE_HOOKUP_OBJECT (mdftroup, button_kdcnfmdf, "button_kdcnfmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (mdftroup, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (mdftroup, image52, "image52");
  GLADE_HOOKUP_OBJECT (mdftroup, label95, "label95");
  GLADE_HOOKUP_OBJECT (mdftroup, combobox_kdtpmdf, "combobox_kdtpmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, label_kdesmdf, "label_kdesmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, combobox_kdesmdf, "combobox_kdesmdf");
  GLADE_HOOKUP_OBJECT (mdftroup, label_kddvmdf, "label_kddvmdf");

  return mdftroup;
}

GtkWidget*
create_rechtroup (void)
{
  GtkWidget *rechtroup;
  GtkWidget *fixed14;
  GtkWidget *label_kdtxtrech;
  GtkWidget *treeview_kdtxtrech;
  GtkWidget *label_khidrech;
  GtkWidget *entry_kdidrech;
  GtkWidget *button_kdcnfrech;
  GtkWidget *alignment76;
  GtkWidget *hbox76;
  GtkWidget *image102;
  GtkWidget *label187;
  GtkWidget *button_kdretrech;
  GtkWidget *alignment41;
  GtkWidget *hbox41;
  GtkWidget *image55;
  GtkWidget *label98;

  rechtroup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (rechtroup, 750, 430);
  gtk_window_set_title (GTK_WINDOW (rechtroup), _("Recherche troupeaux"));

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (rechtroup), fixed14);

  label_kdtxtrech = gtk_label_new (_("Le champ a recherche est :"));
  gtk_widget_show (label_kdtxtrech);
  gtk_fixed_put (GTK_FIXED (fixed14), label_kdtxtrech, 80, 88);
  gtk_widget_set_size_request (label_kdtxtrech, 177, 49);

  treeview_kdtxtrech = gtk_tree_view_new ();
  gtk_widget_show (treeview_kdtxtrech);
  gtk_fixed_put (GTK_FIXED (fixed14), treeview_kdtxtrech, 0, 152);
  gtk_widget_set_size_request (treeview_kdtxtrech, 750, 208);

  label_khidrech = gtk_label_new (_("Taper l'identifiant a chercher :"));
  gtk_widget_show (label_khidrech);
  gtk_fixed_put (GTK_FIXED (fixed14), label_khidrech, 40, 32);
  gtk_widget_set_size_request (label_khidrech, 232, 41);

  entry_kdidrech = gtk_entry_new ();
  gtk_widget_show (entry_kdidrech);
  gtk_fixed_put (GTK_FIXED (fixed14), entry_kdidrech, 192, 64);
  gtk_widget_set_size_request (entry_kdidrech, 250, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_kdidrech), 8226);

  button_kdcnfrech = gtk_button_new ();
  gtk_widget_show (button_kdcnfrech);
  gtk_fixed_put (GTK_FIXED (fixed14), button_kdcnfrech, 488, 64);
  gtk_widget_set_size_request (button_kdcnfrech, 105, 29);

  alignment76 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment76);
  gtk_container_add (GTK_CONTAINER (button_kdcnfrech), alignment76);

  hbox76 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox76);
  gtk_container_add (GTK_CONTAINER (alignment76), hbox76);

  image102 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image102);
  gtk_box_pack_start (GTK_BOX (hbox76), image102, FALSE, FALSE, 0);

  label187 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label187);
  gtk_box_pack_start (GTK_BOX (hbox76), label187, FALSE, FALSE, 0);

  button_kdretrech = gtk_button_new ();
  gtk_widget_show (button_kdretrech);
  gtk_fixed_put (GTK_FIXED (fixed14), button_kdretrech, 664, 8);
  gtk_widget_set_size_request (button_kdretrech, 85, 29);

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (button_kdretrech), alignment41);

  hbox41 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox41);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox41);

  image55 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image55);
  gtk_box_pack_start (GTK_BOX (hbox41), image55, FALSE, FALSE, 0);

  label98 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label98);
  gtk_box_pack_start (GTK_BOX (hbox41), label98, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview_kdtxtrech, "row_activated",
                    G_CALLBACK (on_treeview_kdtxtrech_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button_kdcnfrech, "clicked",
                    G_CALLBACK (on_button_kdcnfrech_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_kdretrech, "clicked",
                    G_CALLBACK (on_button_kdretrech_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rechtroup, rechtroup, "rechtroup");
  GLADE_HOOKUP_OBJECT (rechtroup, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (rechtroup, label_kdtxtrech, "label_kdtxtrech");
  GLADE_HOOKUP_OBJECT (rechtroup, treeview_kdtxtrech, "treeview_kdtxtrech");
  GLADE_HOOKUP_OBJECT (rechtroup, label_khidrech, "label_khidrech");
  GLADE_HOOKUP_OBJECT (rechtroup, entry_kdidrech, "entry_kdidrech");
  GLADE_HOOKUP_OBJECT (rechtroup, button_kdcnfrech, "button_kdcnfrech");
  GLADE_HOOKUP_OBJECT (rechtroup, alignment76, "alignment76");
  GLADE_HOOKUP_OBJECT (rechtroup, hbox76, "hbox76");
  GLADE_HOOKUP_OBJECT (rechtroup, image102, "image102");
  GLADE_HOOKUP_OBJECT (rechtroup, label187, "label187");
  GLADE_HOOKUP_OBJECT (rechtroup, button_kdretrech, "button_kdretrech");
  GLADE_HOOKUP_OBJECT (rechtroup, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (rechtroup, hbox41, "hbox41");
  GLADE_HOOKUP_OBJECT (rechtroup, image55, "image55");
  GLADE_HOOKUP_OBJECT (rechtroup, label98, "label98");

  return rechtroup;
}

GtkWidget*
create_supptroup (void)
{
  GtkWidget *supptroup;
  GtkWidget *fixed26;
  GtkWidget *label_khtxtsp;
  GtkWidget *entry_khidsp;
  GtkWidget *button_khcnfsp;
  GtkWidget *alignment74;
  GtkWidget *hbox74;
  GtkWidget *image100;
  GtkWidget *label185;
  GtkWidget *button_khanlsp;
  GtkWidget *alignment75;
  GtkWidget *hbox75;
  GtkWidget *image101;
  GtkWidget *label186;
  GtkWidget *label_khcnfsp;

  supptroup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (supptroup), _("Supprimer troupeaux"));

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (supptroup), fixed26);

  label_khtxtsp = gtk_label_new (_("Tapez l'identifiant a supprimer"));
  gtk_widget_show (label_khtxtsp);
  gtk_fixed_put (GTK_FIXED (fixed26), label_khtxtsp, 64, 8);
  gtk_widget_set_size_request (label_khtxtsp, 232, 40);

  entry_khidsp = gtk_entry_new ();
  gtk_widget_show (entry_khidsp);
  gtk_fixed_put (GTK_FIXED (fixed26), entry_khidsp, 104, 56);
  gtk_widget_set_size_request (entry_khidsp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_khidsp), 8226);

  button_khcnfsp = gtk_button_new ();
  gtk_widget_show (button_khcnfsp);
  gtk_fixed_put (GTK_FIXED (fixed26), button_khcnfsp, 120, 248);
  gtk_widget_set_size_request (button_khcnfsp, 105, 29);

  alignment74 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment74);
  gtk_container_add (GTK_CONTAINER (button_khcnfsp), alignment74);

  hbox74 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox74);
  gtk_container_add (GTK_CONTAINER (alignment74), hbox74);

  image100 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image100);
  gtk_box_pack_start (GTK_BOX (hbox74), image100, FALSE, FALSE, 0);

  label185 = gtk_label_new_with_mnemonic (_("confirmer"));
  gtk_widget_show (label185);
  gtk_box_pack_start (GTK_BOX (hbox74), label185, FALSE, FALSE, 0);

  button_khanlsp = gtk_button_new ();
  gtk_widget_show (button_khanlsp);
  gtk_fixed_put (GTK_FIXED (fixed26), button_khanlsp, 264, 248);
  gtk_widget_set_size_request (button_khanlsp, 105, 29);

  alignment75 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment75);
  gtk_container_add (GTK_CONTAINER (button_khanlsp), alignment75);

  hbox75 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox75);
  gtk_container_add (GTK_CONTAINER (alignment75), hbox75);

  image101 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image101);
  gtk_box_pack_start (GTK_BOX (hbox75), image101, FALSE, FALSE, 0);

  label186 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label186);
  gtk_box_pack_start (GTK_BOX (hbox75), label186, FALSE, FALSE, 0);

  label_khcnfsp = gtk_label_new ("");
  gtk_widget_show (label_khcnfsp);
  gtk_fixed_put (GTK_FIXED (fixed26), label_khcnfsp, 64, 136);
  gtk_widget_set_size_request (label_khcnfsp, 264, 48);

  g_signal_connect ((gpointer) button_khcnfsp, "clicked",
                    G_CALLBACK (on_button_khcnfsp_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_khanlsp, "clicked",
                    G_CALLBACK (on_button_khanlsp_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supptroup, supptroup, "supptroup");
  GLADE_HOOKUP_OBJECT (supptroup, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (supptroup, label_khtxtsp, "label_khtxtsp");
  GLADE_HOOKUP_OBJECT (supptroup, entry_khidsp, "entry_khidsp");
  GLADE_HOOKUP_OBJECT (supptroup, button_khcnfsp, "button_khcnfsp");
  GLADE_HOOKUP_OBJECT (supptroup, alignment74, "alignment74");
  GLADE_HOOKUP_OBJECT (supptroup, hbox74, "hbox74");
  GLADE_HOOKUP_OBJECT (supptroup, image100, "image100");
  GLADE_HOOKUP_OBJECT (supptroup, label185, "label185");
  GLADE_HOOKUP_OBJECT (supptroup, button_khanlsp, "button_khanlsp");
  GLADE_HOOKUP_OBJECT (supptroup, alignment75, "alignment75");
  GLADE_HOOKUP_OBJECT (supptroup, hbox75, "hbox75");
  GLADE_HOOKUP_OBJECT (supptroup, image101, "image101");
  GLADE_HOOKUP_OBJECT (supptroup, label186, "label186");
  GLADE_HOOKUP_OBJECT (supptroup, label_khcnfsp, "label_khcnfsp");

  return supptroup;
}

