/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gtroup (void);
GtkWidget* create_ajttroup (void);
GtkWidget* create_mdftroup (void);
GtkWidget* create_rechtroup (void);
GtkWidget* create_supptroup (void);
