/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_geqagr (void);
GtkWidget* create_ajeqag (void);
GtkWidget* create_mdfeqag (void);
GtkWidget* create_recheqag (void);
GtkWidget* create_suppeqag (void);
