/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_fenetre_ajout (void)
{
  GtkWidget *fenetre_ajout;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label4;
  GtkWidget *label6;
  GtkWidget *nom;
  GtkWidget *nombre;
  GtkObject *periode_adj;
  GtkWidget *periode;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *id;
  GtkWidget *label12;
  GtkWidget *emplacement;
  GtkWidget *radio1;
  GSList *radio1_group = NULL;
  GtkWidget *radio2;
  GtkWidget *radio3;
  GtkWidget *checkbutton1;
  GtkWidget *afficher;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label9;
  GtkWidget *ajouter;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *label7;
  GtkWidget *label5;

  fenetre_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_ajout), _("window1"));
  gtk_window_set_default_size (GTK_WINDOW (fenetre_ajout), 600, 600);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (fenetre_ajout), fixed1);

  label1 = gtk_label_new (_("Nom de plante :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 100, 100);
  gtk_widget_set_size_request (label1, 150, 30);

  label2 = gtk_label_new (_("Nombre de plantes :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 100, 150);
  gtk_widget_set_size_request (label2, 150, 30);

  label4 = gtk_label_new (_("Periode de plantation :"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed1), label4, 100, 200);
  gtk_widget_set_size_request (label4, 154, 32);

  label6 = gtk_label_new (_("Choisir la date :"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed1), label6, 100, 300);
  gtk_widget_set_size_request (label6, 150, 30);

  nom = gtk_entry_new ();
  gtk_widget_show (nom);
  gtk_fixed_put (GTK_FIXED (fixed1), nom, 250, 100);
  gtk_widget_set_size_request (nom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom), 8226);

  nombre = gtk_entry_new ();
  gtk_widget_show (nombre);
  gtk_fixed_put (GTK_FIXED (fixed1), nombre, 250, 150);
  gtk_widget_set_size_request (nombre, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nombre), 8226);

  periode_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  periode = gtk_spin_button_new (GTK_ADJUSTMENT (periode_adj), 1, 0);
  gtk_widget_show (periode);
  gtk_fixed_put (GTK_FIXED (fixed1), periode, 260, 200);
  gtk_widget_set_size_request (periode, 50, 30);

  jour_adj = gtk_adjustment_new (17, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed1), jour, 250, 300);
  gtk_widget_set_size_request (jour, 50, 27);

  mois_adj = gtk_adjustment_new (3, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed1), mois, 300, 300);
  gtk_widget_set_size_request (mois, 50, 27);

  annee_adj = gtk_adjustment_new (2019, 2000, 2100, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed1), annee, 350, 300);
  gtk_widget_set_size_request (annee, 70, 27);

  id = gtk_entry_new ();
  gtk_widget_show (id);
  gtk_fixed_put (GTK_FIXED (fixed1), id, 250, 50);
  gtk_widget_set_size_request (id, 100, 30);
  gtk_entry_set_invisible_char (GTK_ENTRY (id), 8226);

  label12 = gtk_label_new (_("Id:"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 100, 50);
  gtk_widget_set_size_request (label12, 150, 30);

  emplacement = gtk_combo_box_new_text ();
  gtk_widget_show (emplacement);
  gtk_fixed_put (GTK_FIXED (fixed1), emplacement, 250, 250);
  gtk_widget_set_size_request (emplacement, 50, 30);
  gtk_combo_box_append_text (GTK_COMBO_BOX (emplacement), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (emplacement), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (emplacement), _("C"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (emplacement), _("D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (emplacement), _("E"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (emplacement), _("F"));

  radio1 = gtk_radio_button_new_with_mnemonic (NULL, _("6:00=>10:00"));
  gtk_widget_show (radio1);
  gtk_fixed_put (GTK_FIXED (fixed1), radio1, 240, 352);
  gtk_widget_set_size_request (radio1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio1), radio1_group);
  radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio1));

  radio2 = gtk_radio_button_new_with_mnemonic (NULL, _("11:00=>16:00"));
  gtk_widget_show (radio2);
  gtk_fixed_put (GTK_FIXED (fixed1), radio2, 360, 352);
  gtk_widget_set_size_request (radio2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio2), radio1_group);
  radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio2));

  radio3 = gtk_radio_button_new_with_mnemonic (NULL, _("17:00=>19:00"));
  gtk_widget_show (radio3);
  gtk_fixed_put (GTK_FIXED (fixed1), radio3, 480, 352);
  gtk_widget_set_size_request (radio3, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radio3), radio1_group);
  radio1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radio3));

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("everything is clear"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), checkbutton1, 248, 424);
  gtk_widget_set_size_request (checkbutton1, 168, 24);

  afficher = gtk_button_new ();
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed1), afficher, 328, 488);
  gtk_widget_set_size_request (afficher, 150, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (afficher), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-print", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter, 152, 488);
  gtk_widget_set_size_request (ajouter, 150, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  label7 = gtk_label_new (_("Choisir le temps :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 100, 350);
  gtk_widget_set_size_request (label7, 150, 30);

  label5 = gtk_label_new (_("Emplacement :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed1), label5, 104, 248);
  gtk_widget_set_size_request (label5, 150, 30);

  g_signal_connect ((gpointer) radio1, "toggled",
                    G_CALLBACK (on_radio1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio2, "toggled",
                    G_CALLBACK (on_radio2_toggled),
                    NULL);
  g_signal_connect ((gpointer) radio3, "toggled",
                    G_CALLBACK (on_radio3_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1, "toggled",
                    G_CALLBACK (on_checkbutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_ajout, fenetre_ajout, "fenetre_ajout");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label1, "label1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label2, "label2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label4, "label4");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label6, "label6");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, nom, "nom");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, nombre, "nombre");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, periode, "periode");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, jour, "jour");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, mois, "mois");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, annee, "annee");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, id, "id");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label12, "label12");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, emplacement, "emplacement");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, radio1, "radio1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, radio2, "radio2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, radio3, "radio3");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image2, "image2");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label9, "label9");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, image1, "image1");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label8, "label8");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label7, "label7");
  GLADE_HOOKUP_OBJECT (fenetre_ajout, label5, "label5");

  return fenetre_ajout;
}

GtkWidget*
create_fenetre_affiche (void)
{
  GtkWidget *fenetre_affiche;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *label11;
  GtkWidget *label14;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *id1;
  GtkWidget *nom1;
  GtkWidget *nombre1;
  GtkWidget *periode1;
  GtkWidget *emplacement1;
  GtkWidget *date1;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *temps1;
  GtkWidget *label16;
  GtkWidget *actualiser;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label;
  GtkWidget *label19;
  GtkWidget *retour;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;
  GtkWidget *supprimer;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label22;
  GtkWidget *label21;
  GtkWidget *showbutton;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label24;

  fenetre_affiche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (fenetre_affiche), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (fenetre_affiche), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 72, 48);
  gtk_widget_set_size_request (treeview1, 536, 296);

  label11 = gtk_label_new (_("Faire une modification"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 664, 48);
  gtk_widget_set_size_request (label11, 200, 48);

  label14 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 620, 160);
  gtk_widget_set_size_request (label14, 100, 30);

  label13 = gtk_label_new (_("Id:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 620, 120);
  gtk_widget_set_size_request (label13, 100, 30);

  label15 = gtk_label_new (_("Nombre :"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 620, 200);
  gtk_widget_set_size_request (label15, 100, 30);

  id1 = gtk_entry_new ();
  gtk_widget_show (id1);
  gtk_fixed_put (GTK_FIXED (fixed2), id1, 720, 120);
  gtk_widget_set_size_request (id1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (id1), 8226);

  nom1 = gtk_entry_new ();
  gtk_widget_show (nom1);
  gtk_fixed_put (GTK_FIXED (fixed2), nom1, 720, 160);
  gtk_widget_set_size_request (nom1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nom1), 8226);

  nombre1 = gtk_entry_new ();
  gtk_widget_show (nombre1);
  gtk_fixed_put (GTK_FIXED (fixed2), nombre1, 720, 200);
  gtk_widget_set_size_request (nombre1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nombre1), 8226);

  periode1 = gtk_entry_new ();
  gtk_widget_show (periode1);
  gtk_fixed_put (GTK_FIXED (fixed2), periode1, 725, 240);
  gtk_widget_set_size_request (periode1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (periode1), 8226);

  emplacement1 = gtk_entry_new ();
  gtk_widget_show (emplacement1);
  gtk_fixed_put (GTK_FIXED (fixed2), emplacement1, 720, 280);
  gtk_widget_set_size_request (emplacement1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (emplacement1), 8226);

  date1 = gtk_entry_new ();
  gtk_widget_show (date1);
  gtk_fixed_put (GTK_FIXED (fixed2), date1, 720, 320);
  gtk_widget_set_size_request (date1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (date1), 8226);

  label17 = gtk_label_new (_("Emplacement: "));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 620, 280);
  gtk_widget_set_size_request (label17, 100, 30);

  label18 = gtk_label_new (_("La date :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 620, 320);
  gtk_widget_set_size_request (label18, 100, 30);

  temps1 = gtk_entry_new ();
  gtk_widget_show (temps1);
  gtk_fixed_put (GTK_FIXED (fixed2), temps1, 720, 360);
  gtk_widget_set_size_request (temps1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (temps1), 8226);

  label16 = gtk_label_new (_("Periode(jours):"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 608, 240);
  gtk_widget_set_size_request (label16, 110, 30);

  actualiser = gtk_button_new ();
  gtk_widget_show (actualiser);
  gtk_fixed_put (GTK_FIXED (fixed2), actualiser, 936, 224);
  gtk_widget_set_size_request (actualiser, 150, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (actualiser), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label);
  gtk_box_pack_start (GTK_BOX (hbox4), label, FALSE, FALSE, 0);

  label19 = gtk_label_new (_("Temps:"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 600, 360);
  gtk_widget_set_size_request (label19, 150, 30);

  retour = gtk_button_new ();
  gtk_widget_show (retour);
  gtk_fixed_put (GTK_FIXED (fixed2), retour, 80, 376);
  gtk_widget_set_size_request (retour, 150, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (retour), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), supprimer, 256, 376);
  gtk_widget_set_size_request (supprimer, 150, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox5), label22, FALSE, FALSE, 0);

  label21 = gtk_label_new ("");
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed2), label21, 520, 400);
  gtk_widget_set_size_request (label21, 512, 200);

  showbutton = gtk_button_new ();
  gtk_widget_show (showbutton);
  gtk_fixed_put (GTK_FIXED (fixed2), showbutton, 280, 472);
  gtk_widget_set_size_request (showbutton, 176, 80);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (showbutton), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Affiche ann\303\251e seche "));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox6), label24, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) actualiser, "clicked",
                    G_CALLBACK (on_actualiser_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour, "clicked",
                    G_CALLBACK (on_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) showbutton, "clicked",
                    G_CALLBACK (on_showbutton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (fenetre_affiche, fenetre_affiche, "fenetre_affiche");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label11, "label11");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label14, "label14");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label13, "label13");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label15, "label15");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, id1, "id1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, nom1, "nom1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, nombre1, "nombre1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, periode1, "periode1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, emplacement1, "emplacement1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, date1, "date1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label17, "label17");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label18, "label18");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, temps1, "temps1");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label16, "label16");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, actualiser, "actualiser");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, image4, "image4");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label, "label");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label19, "label19");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, retour, "retour");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, image3, "image3");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label10, "label10");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, image5, "image5");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label22, "label22");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label21, "label21");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, showbutton, "showbutton");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, image6, "image6");
  GLADE_HOOKUP_OBJECT (fenetre_affiche, label24, "label24");

  return fenetre_affiche;
}

