/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *ajouter1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *modifier1;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *supprimer1;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *consulter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label6;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label7;
  GtkWidget *button8_al;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image23;
  GtkWidget *label43;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("Gestion de capteur"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  label1 = gtk_label_new (_("Bienvenue au gestion de capteur"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 136, 32);
  gtk_widget_set_size_request (label1, 272, 40);

  ajouter1 = gtk_button_new ();
  gtk_widget_show (ajouter1);
  gtk_fixed_put (GTK_FIXED (fixed1), ajouter1, 152, 80);
  gtk_widget_set_size_request (ajouter1, 224, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (ajouter1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter un capteur"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  modifier1 = gtk_button_new ();
  gtk_widget_show (modifier1);
  gtk_fixed_put (GTK_FIXED (fixed1), modifier1, 152, 160);
  gtk_widget_set_size_request (modifier1, 224, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (modifier1), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Modifier un capteur"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  supprimer1 = gtk_button_new ();
  gtk_widget_show (supprimer1);
  gtk_fixed_put (GTK_FIXED (fixed1), supprimer1, 152, 240);
  gtk_widget_set_size_request (supprimer1, 224, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (supprimer1), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer un capteur"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  consulter = gtk_button_new ();
  gtk_widget_show (consulter);
  gtk_fixed_put (GTK_FIXED (fixed1), consulter, 152, 320);
  gtk_widget_set_size_request (consulter, 224, 64);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (consulter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Rechercher un capteur"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_fixed_put (GTK_FIXED (fixed1), button5, 24, 448);
  gtk_widget_set_size_request (button5, 80, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-media-previous", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox5), label6, FALSE, FALSE, 0);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed1), button6, 440, 448);
  gtk_widget_set_size_request (button6, 80, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox6), label7, FALSE, FALSE, 0);

  button8_al = gtk_button_new ();
  gtk_widget_show (button8_al);
  gtk_fixed_put (GTK_FIXED (fixed1), button8_al, 152, 408);
  gtk_widget_set_size_request (button8_al, 224, 56);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (button8_al), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image23 = gtk_image_new_from_stock ("gtk-select-color", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox23), image23, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Capteur Alarmante"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox23), label43, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ajouter1, "clicked",
                    G_CALLBACK (on_ajouter1_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier1, "clicked",
                    G_CALLBACK (on_modifier1_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer1, "clicked",
                    G_CALLBACK (on_supprimer1_clicked),
                    NULL);
  g_signal_connect ((gpointer) consulter, "clicked",
                    G_CALLBACK (on_consulter_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8_al, "clicked",
                    G_CALLBACK (on_button8_al_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, ajouter1, "ajouter1");
  GLADE_HOOKUP_OBJECT (window1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window1, image1, "image1");
  GLADE_HOOKUP_OBJECT (window1, label2, "label2");
  GLADE_HOOKUP_OBJECT (window1, modifier1, "modifier1");
  GLADE_HOOKUP_OBJECT (window1, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window1, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window1, image2, "image2");
  GLADE_HOOKUP_OBJECT (window1, label3, "label3");
  GLADE_HOOKUP_OBJECT (window1, supprimer1, "supprimer1");
  GLADE_HOOKUP_OBJECT (window1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window1, image3, "image3");
  GLADE_HOOKUP_OBJECT (window1, label4, "label4");
  GLADE_HOOKUP_OBJECT (window1, consulter, "consulter");
  GLADE_HOOKUP_OBJECT (window1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window1, image4, "image4");
  GLADE_HOOKUP_OBJECT (window1, label5, "label5");
  GLADE_HOOKUP_OBJECT (window1, button5, "button5");
  GLADE_HOOKUP_OBJECT (window1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window1, image5, "image5");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, button6, "button6");
  GLADE_HOOKUP_OBJECT (window1, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window1, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window1, image6, "image6");
  GLADE_HOOKUP_OBJECT (window1, label7, "label7");
  GLADE_HOOKUP_OBJECT (window1, button8_al, "button8_al");
  GLADE_HOOKUP_OBJECT (window1, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (window1, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (window1, image23, "image23");
  GLADE_HOOKUP_OBJECT (window1, label43, "label43");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkWidget *entry_id;
  GtkWidget *entry_mq;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkObject *spinbutton3_adj;
  GtkWidget *spinbutton3;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *radiobutton1;
  GSList *radiobutton1_group = NULL;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image21;
  GtkWidget *label41;
  GtkWidget *radiobutton2;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image22;
  GtkWidget *label42;
  GtkWidget *label17;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *label14;
  GtkWidget *label16;
  GtkWidget *combobox_min;
  GtkWidget *label18;
  GtkWidget *combobox_max;
  GtkWidget *label19;
  GtkWidget *combobox7;
  GtkWidget *ajout;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label20;
  GtkWidget *button7_ret;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label34;
  GtkWidget *modif;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label21;
  GtkWidget *button_affich1;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label35;
  GtkWidget *Msg;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("Formulaire d'ajout et de modification"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  entry_id = gtk_entry_new ();
  gtk_widget_show (entry_id);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_id, 224, 24);
  gtk_widget_set_size_request (entry_id, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id), 8226);

  entry_mq = gtk_entry_new ();
  gtk_widget_show (entry_mq);
  gtk_fixed_put (GTK_FIXED (fixed2), entry_mq, 224, 64);
  gtk_widget_set_size_request (entry_mq, 160, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_mq), 8226);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1, 280, 144);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  spinbutton2_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton2, 376, 144);
  gtk_widget_set_size_request (spinbutton2, 60, 27);

  spinbutton3_adj = gtk_adjustment_new (2010, 2010, 2050, 1, 10, 10);
  spinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton3_adj), 1, 0);
  gtk_widget_show (spinbutton3);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton3, 488, 144);
  gtk_widget_set_size_request (spinbutton3, 60, 27);

  label8 = gtk_label_new (_("Identifiant:"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 128, 24);
  gtk_widget_set_size_request (label8, 104, 32);

  label9 = gtk_label_new (_("Marque:"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 152, 64);
  gtk_widget_set_size_request (label9, 80, 32);

  label10 = gtk_label_new (_("Type:"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 176, 96);
  gtk_widget_set_size_request (label10, 56, 40);

  radiobutton1 = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1, 240, 104);
  gtk_widget_set_size_request (radiobutton1, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1));

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (radiobutton1), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image21 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox21), image21, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Temperature"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox21), label41, FALSE, FALSE, 0);

  radiobutton2 = gtk_radio_button_new (NULL);
  gtk_widget_show (radiobutton2);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2, 384, 104);
  gtk_widget_set_size_request (radiobutton2, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2), radiobutton1_group);
  radiobutton1_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2));

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (radiobutton2), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image22 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox22), image22, FALSE, FALSE, 0);

  label42 = gtk_label_new_with_mnemonic (_("Humidite"));
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox22), label42, FALSE, FALSE, 0);

  label17 = gtk_label_new (_("Valeur minimale:"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed2), label17, 80, 184);
  gtk_widget_set_size_request (label17, 136, 32);

  label13 = gtk_label_new (_("Date d'installation:"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 88, 136);
  gtk_widget_set_size_request (label13, 136, 40);

  label15 = gtk_label_new (_("Mois:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 336, 144);
  gtk_widget_set_size_request (label15, 48, 24);

  label14 = gtk_label_new (_("Jours:"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 232, 136);
  gtk_widget_set_size_request (label14, 48, 40);

  label16 = gtk_label_new (_("Ann\303\251e:"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed2), label16, 440, 144);
  gtk_widget_set_size_request (label16, 48, 24);

  combobox_min = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_min);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_min, 208, 184);
  gtk_widget_set_size_request (combobox_min, 50, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("0"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("6"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("7"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("8"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("9"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_min), _("20"));

  label18 = gtk_label_new (_("Valeur maximale:"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed2), label18, 264, 184);
  gtk_widget_set_size_request (label18, 136, 32);

  combobox_max = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_max);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox_max, 400, 184);
  gtk_widget_set_size_request (combobox_max, 50, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("31"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("32"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("33"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("34"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("35"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("36"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("37"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("38"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("39"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("40"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("41"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("42"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("43"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("44"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("46"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("47"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("48"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("49"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_max), _("50"));

  label19 = gtk_label_new (_("Zone de couverture:"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed2), label19, 64, 216);
  gtk_widget_set_size_request (label19, 152, 40);

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox7, 216, 224);
  gtk_widget_set_size_request (combobox7, 160, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("ZoneA"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("ZoneB"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("ZoneC"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("ZoneD"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("ZoneE"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("ZoneF"));

  ajout = gtk_button_new ();
  gtk_widget_show (ajout);
  gtk_fixed_put (GTK_FIXED (fixed2), ajout, 232, 272);
  gtk_widget_set_size_request (ajout, 96, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (ajout), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox9), label20, FALSE, FALSE, 0);

  button7_ret = gtk_button_new ();
  gtk_widget_show (button7_ret);
  gtk_fixed_put (GTK_FIXED (fixed2), button7_ret, 128, 272);
  gtk_widget_set_size_request (button7_ret, 88, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button7_ret), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox14), label34, FALSE, FALSE, 0);

  modif = gtk_button_new ();
  gtk_widget_show (modif);
  gtk_fixed_put (GTK_FIXED (fixed2), modif, 344, 272);
  gtk_widget_set_size_request (modif, 88, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (modif), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox10), label21, FALSE, FALSE, 0);

  button_affich1 = gtk_button_new ();
  gtk_widget_show (button_affich1);
  gtk_fixed_put (GTK_FIXED (fixed2), button_affich1, 448, 272);
  gtk_widget_set_size_request (button_affich1, 88, 32);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (button_affich1), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox15), label35, FALSE, FALSE, 0);

  Msg = gtk_label_new ("");
  gtk_widget_show (Msg);
  gtk_fixed_put (GTK_FIXED (fixed2), Msg, 160, 312);
  gtk_widget_set_size_request (Msg, 272, 24);

  g_signal_connect ((gpointer) radiobutton1, "toggled",
                    G_CALLBACK (on_radiobutton1_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2, "toggled",
                    G_CALLBACK (on_radiobutton2_toggled),
                    NULL);
  g_signal_connect ((gpointer) ajout, "clicked",
                    G_CALLBACK (on_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7_ret, "clicked",
                    G_CALLBACK (on_button7_ret_clicked),
                    NULL);
  g_signal_connect ((gpointer) modif, "clicked",
                    G_CALLBACK (on_modif_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_affich1, "clicked",
                    G_CALLBACK (on_button_affich1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, entry_id, "entry_id");
  GLADE_HOOKUP_OBJECT (window2, entry_mq, "entry_mq");
  GLADE_HOOKUP_OBJECT (window2, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window2, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (window2, spinbutton3, "spinbutton3");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2, radiobutton1, "radiobutton1");
  GLADE_HOOKUP_OBJECT (window2, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (window2, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (window2, image21, "image21");
  GLADE_HOOKUP_OBJECT (window2, label41, "label41");
  GLADE_HOOKUP_OBJECT (window2, radiobutton2, "radiobutton2");
  GLADE_HOOKUP_OBJECT (window2, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (window2, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (window2, image22, "image22");
  GLADE_HOOKUP_OBJECT (window2, label42, "label42");
  GLADE_HOOKUP_OBJECT (window2, label17, "label17");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, label16, "label16");
  GLADE_HOOKUP_OBJECT (window2, combobox_min, "combobox_min");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, combobox_max, "combobox_max");
  GLADE_HOOKUP_OBJECT (window2, label19, "label19");
  GLADE_HOOKUP_OBJECT (window2, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (window2, ajout, "ajout");
  GLADE_HOOKUP_OBJECT (window2, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window2, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window2, image9, "image9");
  GLADE_HOOKUP_OBJECT (window2, label20, "label20");
  GLADE_HOOKUP_OBJECT (window2, button7_ret, "button7_ret");
  GLADE_HOOKUP_OBJECT (window2, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (window2, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window2, image14, "image14");
  GLADE_HOOKUP_OBJECT (window2, label34, "label34");
  GLADE_HOOKUP_OBJECT (window2, modif, "modif");
  GLADE_HOOKUP_OBJECT (window2, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window2, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window2, image10, "image10");
  GLADE_HOOKUP_OBJECT (window2, label21, "label21");
  GLADE_HOOKUP_OBJECT (window2, button_affich1, "button_affich1");
  GLADE_HOOKUP_OBJECT (window2, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (window2, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window2, image15, "image15");
  GLADE_HOOKUP_OBJECT (window2, label35, "label35");
  GLADE_HOOKUP_OBJECT (window2, Msg, "Msg");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *label22;
  GtkWidget *entry_supp;
  GtkWidget *supp;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label23;
  GtkWidget *checkbutton_conf;
  GtkWidget *alignment27;
  GtkWidget *hbox27;
  GtkWidget *image27;
  GtkWidget *label50;
  GtkWidget *label52;
  GtkWidget *label53;
  GtkWidget *button9_ret;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label36;
  GtkWidget *button12;
  GtkWidget *alignment28;
  GtkWidget *hbox28;
  GtkWidget *image28;
  GtkWidget *label54;
  GtkWidget *label51;
  GtkWidget *button10_affich;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label37;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("Supprission d'un capteur"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  label22 = gtk_label_new (_("Identifiant \303\240 supprimer:"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed3), label22, 112, 48);
  gtk_widget_set_size_request (label22, 184, 32);

  entry_supp = gtk_entry_new ();
  gtk_widget_show (entry_supp);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_supp, 128, 80);
  gtk_widget_set_size_request (entry_supp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_supp), 8226);

  supp = gtk_button_new ();
  gtk_widget_show (supp);
  gtk_fixed_put (GTK_FIXED (fixed3), supp, 136, 168);
  gtk_widget_set_size_request (supp, 160, 32);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (supp), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox11), label23, FALSE, FALSE, 0);

  checkbutton_conf = gtk_check_button_new ();
  gtk_widget_show (checkbutton_conf);
  gtk_fixed_put (GTK_FIXED (fixed3), checkbutton_conf, 144, 128);
  gtk_widget_set_size_request (checkbutton_conf, 118, 24);

  alignment27 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment27);
  gtk_container_add (GTK_CONTAINER (checkbutton_conf), alignment27);

  hbox27 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox27);
  gtk_container_add (GTK_CONTAINER (alignment27), hbox27);

  image27 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox27), image27, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox27), label50, FALSE, FALSE, 0);

  label52 = gtk_label_new ("");
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed3), label52, 312, 120);
  gtk_widget_set_size_request (label52, 232, 32);

  label53 = gtk_label_new ("");
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed3), label53, 312, 168);
  gtk_widget_set_size_request (label53, 304, 32);

  button9_ret = gtk_button_new ();
  gtk_widget_show (button9_ret);
  gtk_fixed_put (GTK_FIXED (fixed3), button9_ret, 16, 208);
  gtk_widget_set_size_request (button9_ret, 88, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (button9_ret), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox16), label36, FALSE, FALSE, 0);

  button12 = gtk_button_new ();
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed3), button12, 336, 200);
  gtk_widget_set_size_request (button12, 104, 32);

  alignment28 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment28);
  gtk_container_add (GTK_CONTAINER (button12), alignment28);

  hbox28 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox28);
  gtk_container_add (GTK_CONTAINER (alignment28), hbox28);

  image28 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox28), image28, FALSE, FALSE, 0);

  label54 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox28), label54, FALSE, FALSE, 0);

  label51 = gtk_label_new ("");
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed3), label51, 320, 80);
  gtk_widget_set_size_request (label51, 296, 32);

  button10_affich = gtk_button_new ();
  gtk_widget_show (button10_affich);
  gtk_fixed_put (GTK_FIXED (fixed3), button10_affich, 456, 200);
  gtk_widget_set_size_request (button10_affich, 96, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (button10_affich), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-goto-last", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox17), label37, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) supp, "clicked",
                    G_CALLBACK (on_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_conf, "toggled",
                    G_CALLBACK (on_checkbutton_conf_toggled),
                    NULL);
  g_signal_connect ((gpointer) button9_ret, "clicked",
                    G_CALLBACK (on_button9_ret_clicked),
                    NULL);
  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10_affich, "clicked",
                    G_CALLBACK (on_button10_affich_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, label22, "label22");
  GLADE_HOOKUP_OBJECT (window3, entry_supp, "entry_supp");
  GLADE_HOOKUP_OBJECT (window3, supp, "supp");
  GLADE_HOOKUP_OBJECT (window3, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window3, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (window3, image11, "image11");
  GLADE_HOOKUP_OBJECT (window3, label23, "label23");
  GLADE_HOOKUP_OBJECT (window3, checkbutton_conf, "checkbutton_conf");
  GLADE_HOOKUP_OBJECT (window3, alignment27, "alignment27");
  GLADE_HOOKUP_OBJECT (window3, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (window3, image27, "image27");
  GLADE_HOOKUP_OBJECT (window3, label50, "label50");
  GLADE_HOOKUP_OBJECT (window3, label52, "label52");
  GLADE_HOOKUP_OBJECT (window3, label53, "label53");
  GLADE_HOOKUP_OBJECT (window3, button9_ret, "button9_ret");
  GLADE_HOOKUP_OBJECT (window3, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (window3, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window3, image16, "image16");
  GLADE_HOOKUP_OBJECT (window3, label36, "label36");
  GLADE_HOOKUP_OBJECT (window3, button12, "button12");
  GLADE_HOOKUP_OBJECT (window3, alignment28, "alignment28");
  GLADE_HOOKUP_OBJECT (window3, hbox28, "hbox28");
  GLADE_HOOKUP_OBJECT (window3, image28, "image28");
  GLADE_HOOKUP_OBJECT (window3, label54, "label54");
  GLADE_HOOKUP_OBJECT (window3, label51, "label51");
  GLADE_HOOKUP_OBJECT (window3, button10_affich, "button10_affich");
  GLADE_HOOKUP_OBJECT (window3, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (window3, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window3, image17, "image17");
  GLADE_HOOKUP_OBJECT (window3, label37, "label37");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *treeview1;
  GtkWidget *entry_rech;
  GtkWidget *treeview2_rech;
  GtkWidget *label24;
  GtkWidget *recherche;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label25;
  GtkWidget *label_msg;
  GtkWidget *label64;
  GtkWidget *button7;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image19;
  GtkWidget *label39;
  GtkWidget *button8_actu;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image20;
  GtkWidget *label40;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("Liste des capteurs"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 8, 16);
  gtk_widget_set_size_request (treeview1, 792, 296);

  entry_rech = gtk_entry_new ();
  gtk_widget_show (entry_rech);
  gtk_fixed_put (GTK_FIXED (fixed4), entry_rech, 192, 336);
  gtk_widget_set_size_request (entry_rech, 160, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_rech), 8226);

  treeview2_rech = gtk_tree_view_new ();
  gtk_widget_show (treeview2_rech);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview2_rech, 16, 400);
  gtk_widget_set_size_request (treeview2_rech, 784, 48);

  label24 = gtk_label_new (_("Identifiant \303\240 rechercher:"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 24, 336);
  gtk_widget_set_size_request (label24, 176, 24);

  recherche = gtk_button_new ();
  gtk_widget_show (recherche);
  gtk_fixed_put (GTK_FIXED (fixed4), recherche, 376, 336);
  gtk_widget_set_size_request (recherche, 128, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (recherche), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox12), label25, FALSE, FALSE, 0);

  label_msg = gtk_label_new (_("Si le capteur  existe ,le r\303\251sultat  sera affich\303\251 ici:"));
  gtk_widget_show (label_msg);
  gtk_fixed_put (GTK_FIXED (fixed4), label_msg, 16, 360);
  gtk_widget_set_size_request (label_msg, 360, 32);

  label64 = gtk_label_new ("");
  gtk_widget_show (label64);
  gtk_fixed_put (GTK_FIXED (fixed4), label64, 520, 336);
  gtk_widget_set_size_request (label64, 272, 32);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed4), button7, 16, 464);
  gtk_widget_set_size_request (button7, 88, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (button7), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image19 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox19), image19, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox19), label39, FALSE, FALSE, 0);

  button8_actu = gtk_button_new ();
  gtk_widget_show (button8_actu);
  gtk_fixed_put (GTK_FIXED (fixed4), button8_actu, 696, 464);
  gtk_widget_set_size_request (button8_actu, 112, 32);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (button8_actu), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image20 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox20), image20, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox20), label40, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) treeview2_rech, "row_activated",
                    G_CALLBACK (on_treeview2_rech_row_activated),
                    NULL);
  g_signal_connect ((gpointer) recherche, "clicked",
                    G_CALLBACK (on_recherche_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8_actu, "clicked",
                    G_CALLBACK (on_button8_actu_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window4, entry_rech, "entry_rech");
  GLADE_HOOKUP_OBJECT (window4, treeview2_rech, "treeview2_rech");
  GLADE_HOOKUP_OBJECT (window4, label24, "label24");
  GLADE_HOOKUP_OBJECT (window4, recherche, "recherche");
  GLADE_HOOKUP_OBJECT (window4, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (window4, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (window4, image12, "image12");
  GLADE_HOOKUP_OBJECT (window4, label25, "label25");
  GLADE_HOOKUP_OBJECT (window4, label_msg, "label_msg");
  GLADE_HOOKUP_OBJECT (window4, label64, "label64");
  GLADE_HOOKUP_OBJECT (window4, button7, "button7");
  GLADE_HOOKUP_OBJECT (window4, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (window4, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (window4, image19, "image19");
  GLADE_HOOKUP_OBJECT (window4, label39, "label39");
  GLADE_HOOKUP_OBJECT (window4, button8_actu, "button8_actu");
  GLADE_HOOKUP_OBJECT (window4, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (window4, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (window4, image20, "image20");
  GLADE_HOOKUP_OBJECT (window4, label40, "label40");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *button11;
  GtkWidget *alignment24;
  GtkWidget *hbox24;
  GtkWidget *image24;
  GtkWidget *label47;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkWidget *label56;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkWidget *label57;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label58;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *button9_tm;
  GtkWidget *alignment25;
  GtkWidget *hbox25;
  GtkWidget *image25;
  GtkWidget *label48;
  GtkWidget *label44;
  GtkWidget *label59;
  GtkWidget *button10;
  GtkWidget *alignment26;
  GtkWidget *hbox26;
  GtkWidget *image26;
  GtkWidget *label49;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *label61;
  GtkWidget *label60;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label55;
  GtkWidget *label45;
  GtkWidget *label46;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("Les capteurs alarmantes"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);

  button11 = gtk_button_new ();
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed5), button11, 16, 392);
  gtk_widget_set_size_request (button11, 74, 29);

  alignment24 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment24);
  gtk_container_add (GTK_CONTAINER (button11), alignment24);

  hbox24 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox24);
  gtk_container_add (GTK_CONTAINER (alignment24), hbox24);

  image24 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox24), image24, FALSE, FALSE, 0);

  label47 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox24), label47, FALSE, FALSE, 0);

  spinbutton4_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton4, 104, 64);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  label56 = gtk_label_new (_("Valeur Min2:"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed5), label56, 160, 56);
  gtk_widget_set_size_request (label56, 96, 40);

  spinbutton5_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton5, 256, 64);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  label57 = gtk_label_new (_("Valeur Max1:"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed5), label57, 320, 56);
  gtk_widget_set_size_request (label57, 96, 40);

  spinbutton6_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton6, 416, 64);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label58 = gtk_label_new (_("Valeur Max2:"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed5), label58, 480, 56);
  gtk_widget_set_size_request (label58, 88, 40);

  spinbutton7_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton7, 576, 64);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  button9_tm = gtk_button_new ();
  gtk_widget_show (button9_tm);
  gtk_fixed_put (GTK_FIXED (fixed5), button9_tm, 216, 104);
  gtk_widget_set_size_request (button9_tm, 200, 56);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (button9_tm), alignment25);

  hbox25 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox25);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox25);

  image25 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox25), image25, FALSE, FALSE, 0);

  label48 = gtk_label_new_with_mnemonic (_("Capteur de temperature"));
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox25), label48, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("Le capteur de temperature:"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed5), label44, 200, 24);
  gtk_widget_set_size_request (label44, 224, 24);

  label59 = gtk_label_new (_("Le capteur de humidit\303\251:"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed5), label59, 216, 200);
  gtk_widget_set_size_request (label59, 208, 24);

  button10 = gtk_button_new ();
  gtk_widget_show (button10);
  gtk_fixed_put (GTK_FIXED (fixed5), button10, 216, 272);
  gtk_widget_set_size_request (button10, 208, 56);

  alignment26 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment26);
  gtk_container_add (GTK_CONTAINER (button10), alignment26);

  hbox26 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox26);
  gtk_container_add (GTK_CONTAINER (alignment26), hbox26);

  image26 = gtk_image_new_from_stock ("gtk-sort-descending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox26), image26, FALSE, FALSE, 0);

  label49 = gtk_label_new_with_mnemonic (_("Capteur de humidit\303\251"));
  gtk_widget_show (label49);
  gtk_box_pack_start (GTK_BOX (hbox26), label49, FALSE, FALSE, 0);

  spinbutton8_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton8, 104, 240);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton9, 256, 240);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  label61 = gtk_label_new (_("Valeur Min2:"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed5), label61, 168, 232);
  gtk_widget_set_size_request (label61, 88, 40);

  label60 = gtk_label_new (_("Valeur Min1:"));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (fixed5), label60, 8, 232);
  gtk_widget_set_size_request (label60, 104, 40);

  spinbutton10_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton10, 416, 240);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  spinbutton11_adj = gtk_adjustment_new (0, -300, 300, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed5), spinbutton11, 576, 240);
  gtk_widget_set_size_request (spinbutton11, 60, 27);

  label62 = gtk_label_new (_("Valeur Max1:"));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (fixed5), label62, 304, 232);
  gtk_widget_set_size_request (label62, 120, 40);

  label63 = gtk_label_new (_("Valeur Max2:"));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (fixed5), label63, 480, 232);
  gtk_widget_set_size_request (label63, 88, 40);

  label55 = gtk_label_new (_("Valeur Min1:"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed5), label55, 8, 56);
  gtk_widget_set_size_request (label55, 96, 40);

  label45 = gtk_label_new (_("R\303\251sultat:"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed5), label45, 136, 160);
  gtk_widget_set_size_request (label45, 360, 40);

  label46 = gtk_label_new (_("R\303\251sultat:"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed5), label46, 144, 336);
  gtk_widget_set_size_request (label46, 360, 40);

  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9_tm, "clicked",
                    G_CALLBACK (on_button9_tm_clicked),
                    NULL);
  g_signal_connect ((gpointer) button10, "clicked",
                    G_CALLBACK (on_button10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, button11, "button11");
  GLADE_HOOKUP_OBJECT (window5, alignment24, "alignment24");
  GLADE_HOOKUP_OBJECT (window5, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window5, image24, "image24");
  GLADE_HOOKUP_OBJECT (window5, label47, "label47");
  GLADE_HOOKUP_OBJECT (window5, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (window5, label56, "label56");
  GLADE_HOOKUP_OBJECT (window5, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (window5, label57, "label57");
  GLADE_HOOKUP_OBJECT (window5, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (window5, label58, "label58");
  GLADE_HOOKUP_OBJECT (window5, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (window5, button9_tm, "button9_tm");
  GLADE_HOOKUP_OBJECT (window5, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (window5, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window5, image25, "image25");
  GLADE_HOOKUP_OBJECT (window5, label48, "label48");
  GLADE_HOOKUP_OBJECT (window5, label44, "label44");
  GLADE_HOOKUP_OBJECT (window5, label59, "label59");
  GLADE_HOOKUP_OBJECT (window5, button10, "button10");
  GLADE_HOOKUP_OBJECT (window5, alignment26, "alignment26");
  GLADE_HOOKUP_OBJECT (window5, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window5, image26, "image26");
  GLADE_HOOKUP_OBJECT (window5, label49, "label49");
  GLADE_HOOKUP_OBJECT (window5, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (window5, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (window5, label61, "label61");
  GLADE_HOOKUP_OBJECT (window5, label60, "label60");
  GLADE_HOOKUP_OBJECT (window5, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (window5, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (window5, label62, "label62");
  GLADE_HOOKUP_OBJECT (window5, label63, "label63");
  GLADE_HOOKUP_OBJECT (window5, label55, "label55");
  GLADE_HOOKUP_OBJECT (window5, label45, "label45");
  GLADE_HOOKUP_OBJECT (window5, label46, "label46");

  return window5;
}

