/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_FTfenetre_ajout (void);
GtkWidget* create_FTfenetre_afficher (void);
GtkWidget* create_FTfenetre_abs (void);
GtkWidget* create_FTFenetre_erreur (void);
