/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowmaingc (void)
{
  GtkWidget *windowmaingc;
  GtkWidget *fixed1;
  GtkWidget *buttonretourgc;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label1;
  GtkWidget *buttonajoutergc;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *buttonsupprimergc;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label5;
  GtkWidget *buttonrecherchergc;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label6;
  GtkWidget *buttonmodifiergc;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label4;
  GtkWidget *buttonaffichergc;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label2;
  GtkWidget *labelbienvenue;

  windowmaingc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowmaingc), _("Main"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (windowmaingc), fixed1);

  buttonretourgc = gtk_button_new ();
  gtk_widget_show (buttonretourgc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonretourgc, 8, 8);
  gtk_widget_set_size_request (buttonretourgc, 80, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonretourgc), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label1 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox1), label1, FALSE, FALSE, 0);

  buttonajoutergc = gtk_button_new ();
  gtk_widget_show (buttonajoutergc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonajoutergc, 120, 152);
  gtk_widget_set_size_request (buttonajoutergc, 88, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttonajoutergc), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  buttonsupprimergc = gtk_button_new ();
  gtk_widget_show (buttonsupprimergc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonsupprimergc, 120, 216);
  gtk_widget_set_size_request (buttonsupprimergc, 104, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttonsupprimergc), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox5), label5, FALSE, FALSE, 0);

  buttonrecherchergc = gtk_button_new ();
  gtk_widget_show (buttonrecherchergc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonrecherchergc, 264, 216);
  gtk_widget_set_size_request (buttonrecherchergc, 112, 37);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttonrecherchergc), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_(" Rechercher"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox6), label6, FALSE, FALSE, 0);

  buttonmodifiergc = gtk_button_new ();
  gtk_widget_show (buttonmodifiergc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonmodifiergc, 280, 152);
  gtk_widget_set_size_request (buttonmodifiergc, 96, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonmodifiergc), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_(" Modifier"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox4), label4, FALSE, FALSE, 0);

  buttonaffichergc = gtk_button_new ();
  gtk_widget_show (buttonaffichergc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonaffichergc, 408, 8);
  gtk_widget_set_size_request (buttonaffichergc, 88, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonaffichergc), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox2), label2, FALSE, FALSE, 0);

  labelbienvenue = gtk_label_new (_("Bienvenue"));
  gtk_widget_show (labelbienvenue);
  gtk_fixed_put (GTK_FIXED (fixed1), labelbienvenue, 192, 80);
  gtk_widget_set_size_request (labelbienvenue, 96, 32);

  g_signal_connect ((gpointer) buttonajoutergc, "clicked",
                    G_CALLBACK (on_buttonajoutergc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimergc, "clicked",
                    G_CALLBACK (on_buttonsupprimergc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrecherchergc, "clicked",
                    G_CALLBACK (on_buttonrecherchergc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifiergc, "clicked",
                    G_CALLBACK (on_buttonmodifiergc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonaffichergc, "clicked",
                    G_CALLBACK (on_buttonaffichergc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowmaingc, windowmaingc, "windowmaingc");
  GLADE_HOOKUP_OBJECT (windowmaingc, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (windowmaingc, buttonretourgc, "buttonretourgc");
  GLADE_HOOKUP_OBJECT (windowmaingc, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowmaingc, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowmaingc, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowmaingc, label1, "label1");
  GLADE_HOOKUP_OBJECT (windowmaingc, buttonajoutergc, "buttonajoutergc");
  GLADE_HOOKUP_OBJECT (windowmaingc, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowmaingc, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowmaingc, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowmaingc, label3, "label3");
  GLADE_HOOKUP_OBJECT (windowmaingc, buttonsupprimergc, "buttonsupprimergc");
  GLADE_HOOKUP_OBJECT (windowmaingc, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowmaingc, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowmaingc, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowmaingc, label5, "label5");
  GLADE_HOOKUP_OBJECT (windowmaingc, buttonrecherchergc, "buttonrecherchergc");
  GLADE_HOOKUP_OBJECT (windowmaingc, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowmaingc, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowmaingc, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowmaingc, label6, "label6");
  GLADE_HOOKUP_OBJECT (windowmaingc, buttonmodifiergc, "buttonmodifiergc");
  GLADE_HOOKUP_OBJECT (windowmaingc, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowmaingc, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowmaingc, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowmaingc, label4, "label4");
  GLADE_HOOKUP_OBJECT (windowmaingc, buttonaffichergc, "buttonaffichergc");
  GLADE_HOOKUP_OBJECT (windowmaingc, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowmaingc, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowmaingc, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowmaingc, label2, "label2");
  GLADE_HOOKUP_OBJECT (windowmaingc, labelbienvenue, "labelbienvenue");

  return windowmaingc;
}

GtkWidget*
create_windowajoutergc (void)
{
  GtkWidget *windowajoutergc;
  GtkWidget *fixed2;
  GtkWidget *entryidajgc;
  GtkWidget *entryprenomajgc;
  GtkWidget *entrynomajgc;
  GtkWidget *entrymdpajgc;
  GtkWidget *entrynumtelajgc;
  GtkObject *spinbuttondijajgc_adj;
  GtkWidget *spinbuttondijajgc;
  GtkObject *spinbuttondimajgc_adj;
  GtkWidget *spinbuttondimajgc;
  GtkObject *spinbuttondiaajgc_adj;
  GtkWidget *spinbuttondiaajgc;
  GtkWidget *labelprenomajgc;
  GtkWidget *labelnomajgc;
  GtkWidget *labelmdpajgc;
  GtkWidget *labelAgeajgc;
  GtkWidget *labelsexeajgc;
  GtkWidget *labeldiajgc;
  GtkWidget *labelidajgc;
  GtkWidget *buttonafficherajgc;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label16;
  GtkWidget *buttonretourajgc;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label15;
  GtkWidget *radiobuttonfemmeajgc;
  GSList *radiobuttonfemmeajgc_group = NULL;
  GtkWidget *labelnumtelajgc;
  GtkWidget *comboboxageajgc;
  GtkWidget *radiobuttonhommeajgc;
  GtkWidget *label45sat;
  GtkWidget *buttonajouterajgc;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label17;
  GtkWidget *checkbutton1;

  windowajoutergc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowajoutergc), _("Ajouter"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (windowajoutergc), fixed2);

  entryidajgc = gtk_entry_new ();
  gtk_widget_show (entryidajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), entryidajgc, 208, 56);
  gtk_widget_set_size_request (entryidajgc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidajgc), 8226);

  entryprenomajgc = gtk_entry_new ();
  gtk_widget_show (entryprenomajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), entryprenomajgc, 208, 96);
  gtk_widget_set_size_request (entryprenomajgc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomajgc), 8226);

  entrynomajgc = gtk_entry_new ();
  gtk_widget_show (entrynomajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), entrynomajgc, 208, 136);
  gtk_widget_set_size_request (entrynomajgc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomajgc), 8226);

  entrymdpajgc = gtk_entry_new ();
  gtk_widget_show (entrymdpajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), entrymdpajgc, 208, 176);
  gtk_widget_set_size_request (entrymdpajgc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdpajgc), 8226);

  entrynumtelajgc = gtk_entry_new ();
  gtk_widget_show (entrynumtelajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), entrynumtelajgc, 208, 216);
  gtk_widget_set_size_request (entrynumtelajgc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynumtelajgc), 8226);

  spinbuttondijajgc_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttondijajgc = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttondijajgc_adj), 1, 0);
  gtk_widget_show (spinbuttondijajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttondijajgc, 216, 328);
  gtk_widget_set_size_request (spinbuttondijajgc, 60, 27);

  spinbuttondimajgc_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttondimajgc = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttondimajgc_adj), 1, 0);
  gtk_widget_show (spinbuttondimajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttondimajgc, 280, 328);
  gtk_widget_set_size_request (spinbuttondimajgc, 60, 27);

  spinbuttondiaajgc_adj = gtk_adjustment_new (1990, 1990, 2030, 1, 10, 10);
  spinbuttondiaajgc = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttondiaajgc_adj), 1, 0);
  gtk_widget_show (spinbuttondiaajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbuttondiaajgc, 344, 328);
  gtk_widget_set_size_request (spinbuttondiaajgc, 60, 27);

  labelprenomajgc = gtk_label_new (_("Prenom"));
  gtk_widget_show (labelprenomajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), labelprenomajgc, 72, 96);
  gtk_widget_set_size_request (labelprenomajgc, 72, 24);

  labelnomajgc = gtk_label_new (_("Nom"));
  gtk_widget_show (labelnomajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), labelnomajgc, 88, 144);
  gtk_widget_set_size_request (labelnomajgc, 41, 17);

  labelmdpajgc = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (labelmdpajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), labelmdpajgc, 64, 176);
  gtk_widget_set_size_request (labelmdpajgc, 96, 24);

  labelAgeajgc = gtk_label_new (_("Age"));
  gtk_widget_show (labelAgeajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), labelAgeajgc, 80, 296);
  gtk_widget_set_size_request (labelAgeajgc, 49, 17);

  labelsexeajgc = gtk_label_new (_("Sexe"));
  gtk_widget_show (labelsexeajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), labelsexeajgc, 80, 256);
  gtk_widget_set_size_request (labelsexeajgc, 49, 17);

  labeldiajgc = gtk_label_new (_("Date d'inscription"));
  gtk_widget_show (labeldiajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), labeldiajgc, 40, 328);
  gtk_widget_set_size_request (labeldiajgc, 128, 24);

  labelidajgc = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelidajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), labelidajgc, 48, 56);
  gtk_widget_set_size_request (labelidajgc, 113, 24);

  buttonafficherajgc = gtk_button_new ();
  gtk_widget_show (buttonafficherajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonafficherajgc, 392, 8);
  gtk_widget_set_size_request (buttonafficherajgc, 88, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttonafficherajgc), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_(" Afficher"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox8), label16, FALSE, FALSE, 0);

  buttonretourajgc = gtk_button_new ();
  gtk_widget_show (buttonretourajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonretourajgc, 8, 8);
  gtk_widget_set_size_request (buttonretourajgc, 80, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttonretourajgc), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox7), label15, FALSE, FALSE, 0);

  radiobuttonfemmeajgc = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonfemmeajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonfemmeajgc, 288, 256);
  gtk_widget_set_size_request (radiobuttonfemmeajgc, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemmeajgc), radiobuttonfemmeajgc_group);
  radiobuttonfemmeajgc_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemmeajgc));

  labelnumtelajgc = gtk_label_new (_("Numero de telephone"));
  gtk_widget_show (labelnumtelajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), labelnumtelajgc, 32, 216);
  gtk_widget_set_size_request (labelnumtelajgc, 152, 24);

  comboboxageajgc = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxageajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), comboboxageajgc, 211, 288);
  gtk_widget_set_size_request (comboboxageajgc, 50, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("15 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("31"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("32"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("33"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("34"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("35"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("36"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("37"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("38"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("39"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("40"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("41"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("42"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("43"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("44"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("46"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("47"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("48"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("49"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("50"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("51"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("52"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("53"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("54"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("55"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("56"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("57"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("58"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("59"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("60"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("61"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("62"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("63"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("64"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("65"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("66"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("67"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("68"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("69"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("70"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("71"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("72"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("73"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("74"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("75"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("76"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("77"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("78"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("79"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxageajgc), _("80"));

  radiobuttonhommeajgc = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonhommeajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobuttonhommeajgc, 208, 256);
  gtk_widget_set_size_request (radiobuttonhommeajgc, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonhommeajgc), radiobuttonfemmeajgc_group);
  radiobuttonfemmeajgc_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonhommeajgc));

  label45sat = gtk_label_new (_("Satisfaction"));
  gtk_widget_show (label45sat);
  gtk_fixed_put (GTK_FIXED (fixed2), label45sat, 16, 368);
  gtk_widget_set_size_request (label45sat, 96, 24);

  buttonajouterajgc = gtk_button_new ();
  gtk_widget_show (buttonajouterajgc);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonajouterajgc, 224, 400);
  gtk_widget_set_size_request (buttonajouterajgc, 88, 32);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttonajouterajgc), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_(" Ajouter"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox9), label17, FALSE, FALSE, 0);

  checkbutton1 = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkbutton1);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1, 112, 368);
  gtk_widget_set_size_request (checkbutton1, 118, 24);

  g_signal_connect ((gpointer) buttonafficherajgc, "clicked",
                    G_CALLBACK (on_buttonafficherajgc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourajgc, "clicked",
                    G_CALLBACK (on_buttonretourajgc_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonhommeajgc, "toggled",
                    G_CALLBACK (on_radiobuttonhommeajgc_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonajouterajgc, "clicked",
                    G_CALLBACK (on_buttonajouterajgc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowajoutergc, windowajoutergc, "windowajoutergc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (windowajoutergc, entryidajgc, "entryidajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, entryprenomajgc, "entryprenomajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, entrynomajgc, "entrynomajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, entrymdpajgc, "entrymdpajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, entrynumtelajgc, "entrynumtelajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, spinbuttondijajgc, "spinbuttondijajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, spinbuttondimajgc, "spinbuttondimajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, spinbuttondiaajgc, "spinbuttondiaajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, labelprenomajgc, "labelprenomajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, labelnomajgc, "labelnomajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, labelmdpajgc, "labelmdpajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, labelAgeajgc, "labelAgeajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, labelsexeajgc, "labelsexeajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, labeldiajgc, "labeldiajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, labelidajgc, "labelidajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, buttonafficherajgc, "buttonafficherajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (windowajoutergc, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (windowajoutergc, image8, "image8");
  GLADE_HOOKUP_OBJECT (windowajoutergc, label16, "label16");
  GLADE_HOOKUP_OBJECT (windowajoutergc, buttonretourajgc, "buttonretourajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (windowajoutergc, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (windowajoutergc, image7, "image7");
  GLADE_HOOKUP_OBJECT (windowajoutergc, label15, "label15");
  GLADE_HOOKUP_OBJECT (windowajoutergc, radiobuttonfemmeajgc, "radiobuttonfemmeajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, labelnumtelajgc, "labelnumtelajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, comboboxageajgc, "comboboxageajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, radiobuttonhommeajgc, "radiobuttonhommeajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, label45sat, "label45sat");
  GLADE_HOOKUP_OBJECT (windowajoutergc, buttonajouterajgc, "buttonajouterajgc");
  GLADE_HOOKUP_OBJECT (windowajoutergc, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (windowajoutergc, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (windowajoutergc, image9, "image9");
  GLADE_HOOKUP_OBJECT (windowajoutergc, label17, "label17");
  GLADE_HOOKUP_OBJECT (windowajoutergc, checkbutton1, "checkbutton1");

  return windowajoutergc;
}

GtkWidget*
create_windowsupprimergc (void)
{
  GtkWidget *windowsupprimergc;
  GtkWidget *fixed3;
  GtkWidget *entryidsugc;
  GtkWidget *labelidsugc;
  GtkWidget *buttonaffichersugc;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label29;
  GtkWidget *buttonretoursugc;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label28;
  GtkWidget *buttonsupprimersugc;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label31;

  windowsupprimergc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowsupprimergc), _("Supprimer"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (windowsupprimergc), fixed3);

  entryidsugc = gtk_entry_new ();
  gtk_widget_show (entryidsugc);
  gtk_fixed_put (GTK_FIXED (fixed3), entryidsugc, 224, 88);
  gtk_widget_set_size_request (entryidsugc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidsugc), 8226);

  labelidsugc = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelidsugc);
  gtk_fixed_put (GTK_FIXED (fixed3), labelidsugc, 80, 88);
  gtk_widget_set_size_request (labelidsugc, 113, 24);

  buttonaffichersugc = gtk_button_new ();
  gtk_widget_show (buttonaffichersugc);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonaffichersugc, 400, 8);
  gtk_widget_set_size_request (buttonaffichersugc, 88, 32);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonaffichersugc), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_(" Afficher"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox13), label29, FALSE, FALSE, 0);

  buttonretoursugc = gtk_button_new ();
  gtk_widget_show (buttonretoursugc);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonretoursugc, 8, 8);
  gtk_widget_set_size_request (buttonretoursugc, 80, 32);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonretoursugc), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox12), label28, FALSE, FALSE, 0);

  buttonsupprimersugc = gtk_button_new ();
  gtk_widget_show (buttonsupprimersugc);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonsupprimersugc, 256, 136);
  gtk_widget_set_size_request (buttonsupprimersugc, 104, 32);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttonsupprimersugc), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_(" Supprimer"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox14), label31, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonaffichersugc, "clicked",
                    G_CALLBACK (on_buttonaffichersugc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretoursugc, "clicked",
                    G_CALLBACK (on_buttonretoursugc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimersugc, "clicked",
                    G_CALLBACK (on_buttonsupprimersugc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowsupprimergc, windowsupprimergc, "windowsupprimergc");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, entryidsugc, "entryidsugc");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, labelidsugc, "labelidsugc");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, buttonaffichersugc, "buttonaffichersugc");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, image13, "image13");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, buttonretoursugc, "buttonretoursugc");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, image12, "image12");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, label28, "label28");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, buttonsupprimersugc, "buttonsupprimersugc");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, image14, "image14");
  GLADE_HOOKUP_OBJECT (windowsupprimergc, label31, "label31");

  return windowsupprimergc;
}

GtkWidget*
create_windowaffichergc (void)
{
  GtkWidget *windowaffichergc;
  GtkWidget *fixed4;
  GtkWidget *treeview1;
  GtkWidget *entryrechercherafgc;
  GtkWidget *buttonretourafgc;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image20;
  GtkWidget *label44;
  GtkWidget *buttonrechercherafgc;
  GtkWidget *image19;

  windowaffichergc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowaffichergc), _("Afficher"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (windowaffichergc), fixed4);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed4), treeview1, 24, 144);
  gtk_widget_set_size_request (treeview1, 472, 248);

  entryrechercherafgc = gtk_entry_new ();
  gtk_widget_show (entryrechercherafgc);
  gtk_fixed_put (GTK_FIXED (fixed4), entryrechercherafgc, 176, 96);
  gtk_widget_set_size_request (entryrechercherafgc, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryrechercherafgc), 8226);

  buttonretourafgc = gtk_button_new ();
  gtk_widget_show (buttonretourafgc);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonretourafgc, 8, 8);
  gtk_widget_set_size_request (buttonretourafgc, 74, 29);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonretourafgc), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image20 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_box_pack_start (GTK_BOX (hbox19), image20, FALSE, FALSE, 0);

  label44 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox19), label44, FALSE, FALSE, 0);

  buttonrechercherafgc = gtk_button_new ();
  gtk_widget_show (buttonrechercherafgc);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonrechercherafgc, 128, 96);
  gtk_widget_set_size_request (buttonrechercherafgc, 32, 32);

  image19 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (buttonrechercherafgc), image19);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonretourafgc, "clicked",
                    G_CALLBACK (on_buttonretourafgc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrechercherafgc, "clicked",
                    G_CALLBACK (on_buttonrechercherafgc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowaffichergc, windowaffichergc, "windowaffichergc");
  GLADE_HOOKUP_OBJECT (windowaffichergc, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (windowaffichergc, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (windowaffichergc, entryrechercherafgc, "entryrechercherafgc");
  GLADE_HOOKUP_OBJECT (windowaffichergc, buttonretourafgc, "buttonretourafgc");
  GLADE_HOOKUP_OBJECT (windowaffichergc, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (windowaffichergc, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (windowaffichergc, image20, "image20");
  GLADE_HOOKUP_OBJECT (windowaffichergc, label44, "label44");
  GLADE_HOOKUP_OBJECT (windowaffichergc, buttonrechercherafgc, "buttonrechercherafgc");
  GLADE_HOOKUP_OBJECT (windowaffichergc, image19, "image19");

  return windowaffichergc;
}

GtkWidget*
create_windowmodifiergc (void)
{
  GtkWidget *windowmodifiergc;
  GtkWidget *fixed6;
  GtkWidget *entryidmogc;
  GtkWidget *entryprenommogc;
  GtkWidget *entrynommogc;
  GtkWidget *entrymdpmogc;
  GtkWidget *entrynumtelmogc;
  GtkObject *spinbuttondijmogc_adj;
  GtkWidget *spinbuttondijmogc;
  GtkObject *spinbuttondimmogc_adj;
  GtkWidget *spinbuttondimmogc;
  GtkObject *spinbuttondiamogc_adj;
  GtkWidget *spinbuttondiamogc;
  GtkWidget *labelidmogc;
  GtkWidget *labelprenommogc;
  GtkWidget *labelnommogc;
  GtkWidget *labelmdpmogc;
  GtkWidget *labelsexemogc;
  GtkWidget *labelagemogc;
  GtkWidget *labeldimogc;
  GtkWidget *buttonaffichermogc;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label41;
  GtkWidget *buttonretourmogc;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label40;
  GtkWidget *radiobuttonfemmemogc;
  GSList *radiobuttonfemmemogc_group = NULL;
  GtkWidget *labelnumtelmogc;
  GtkWidget *comboboxagemogc;
  GtkWidget *radiobuttonhommemogc;
  GtkWidget *label46sat;
  GtkWidget *buttonmodifiermogc;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label43;
  GtkWidget *checkbutton3;

  windowmodifiergc = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowmodifiergc), _("Modifier"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (windowmodifiergc), fixed6);

  entryidmogc = gtk_entry_new ();
  gtk_widget_show (entryidmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), entryidmogc, 208, 56);
  gtk_widget_set_size_request (entryidmogc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidmogc), 8226);

  entryprenommogc = gtk_entry_new ();
  gtk_widget_show (entryprenommogc);
  gtk_fixed_put (GTK_FIXED (fixed6), entryprenommogc, 208, 96);
  gtk_widget_set_size_request (entryprenommogc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenommogc), 8226);

  entrynommogc = gtk_entry_new ();
  gtk_widget_show (entrynommogc);
  gtk_fixed_put (GTK_FIXED (fixed6), entrynommogc, 208, 136);
  gtk_widget_set_size_request (entrynommogc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynommogc), 8226);

  entrymdpmogc = gtk_entry_new ();
  gtk_widget_show (entrymdpmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), entrymdpmogc, 208, 176);
  gtk_widget_set_size_request (entrymdpmogc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdpmogc), 8226);

  entrynumtelmogc = gtk_entry_new ();
  gtk_widget_show (entrynumtelmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), entrynumtelmogc, 208, 216);
  gtk_widget_set_size_request (entrynumtelmogc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynumtelmogc), 8226);

  spinbuttondijmogc_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbuttondijmogc = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttondijmogc_adj), 1, 0);
  gtk_widget_show (spinbuttondijmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttondijmogc, 216, 328);
  gtk_widget_set_size_request (spinbuttondijmogc, 60, 27);

  spinbuttondimmogc_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttondimmogc = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttondimmogc_adj), 1, 0);
  gtk_widget_show (spinbuttondimmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttondimmogc, 280, 328);
  gtk_widget_set_size_request (spinbuttondimmogc, 60, 27);

  spinbuttondiamogc_adj = gtk_adjustment_new (1990, 1990, 2030, 1, 10, 10);
  spinbuttondiamogc = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttondiamogc_adj), 1, 0);
  gtk_widget_show (spinbuttondiamogc);
  gtk_fixed_put (GTK_FIXED (fixed6), spinbuttondiamogc, 344, 328);
  gtk_widget_set_size_request (spinbuttondiamogc, 60, 27);

  labelidmogc = gtk_label_new (_("Identifiant"));
  gtk_widget_show (labelidmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), labelidmogc, 48, 56);
  gtk_widget_set_size_request (labelidmogc, 113, 24);

  labelprenommogc = gtk_label_new (_("Prenom"));
  gtk_widget_show (labelprenommogc);
  gtk_fixed_put (GTK_FIXED (fixed6), labelprenommogc, 72, 96);
  gtk_widget_set_size_request (labelprenommogc, 72, 24);

  labelnommogc = gtk_label_new (_("Nom"));
  gtk_widget_show (labelnommogc);
  gtk_fixed_put (GTK_FIXED (fixed6), labelnommogc, 88, 144);
  gtk_widget_set_size_request (labelnommogc, 41, 17);

  labelmdpmogc = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (labelmdpmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), labelmdpmogc, 64, 176);
  gtk_widget_set_size_request (labelmdpmogc, 96, 24);

  labelsexemogc = gtk_label_new (_("Sexe"));
  gtk_widget_show (labelsexemogc);
  gtk_fixed_put (GTK_FIXED (fixed6), labelsexemogc, 80, 256);
  gtk_widget_set_size_request (labelsexemogc, 49, 17);

  labelagemogc = gtk_label_new (_("Age"));
  gtk_widget_show (labelagemogc);
  gtk_fixed_put (GTK_FIXED (fixed6), labelagemogc, 80, 296);
  gtk_widget_set_size_request (labelagemogc, 49, 17);

  labeldimogc = gtk_label_new (_("Date d'inscription"));
  gtk_widget_show (labeldimogc);
  gtk_fixed_put (GTK_FIXED (fixed6), labeldimogc, 40, 328);
  gtk_widget_set_size_request (labeldimogc, 128, 24);

  buttonaffichermogc = gtk_button_new ();
  gtk_widget_show (buttonaffichermogc);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonaffichermogc, 392, 8);
  gtk_widget_set_size_request (buttonaffichermogc, 88, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonaffichermogc), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_(" Afficher"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox17), label41, FALSE, FALSE, 0);

  buttonretourmogc = gtk_button_new ();
  gtk_widget_show (buttonretourmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonretourmogc, 8, 8);
  gtk_widget_set_size_request (buttonretourmogc, 80, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonretourmogc), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox16), label40, FALSE, FALSE, 0);

  radiobuttonfemmemogc = gtk_radio_button_new_with_mnemonic (NULL, _("Femme"));
  gtk_widget_show (radiobuttonfemmemogc);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttonfemmemogc, 288, 256);
  gtk_widget_set_size_request (radiobuttonfemmemogc, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonfemmemogc), radiobuttonfemmemogc_group);
  radiobuttonfemmemogc_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonfemmemogc));

  labelnumtelmogc = gtk_label_new (_("Numero de telephone"));
  gtk_widget_show (labelnumtelmogc);
  gtk_fixed_put (GTK_FIXED (fixed6), labelnumtelmogc, 40, 216);
  gtk_widget_set_size_request (labelnumtelmogc, 152, 24);

  comboboxagemogc = gtk_combo_box_new_text ();
  gtk_widget_show (comboboxagemogc);
  gtk_fixed_put (GTK_FIXED (fixed6), comboboxagemogc, 211, 288);
  gtk_widget_set_size_request (comboboxagemogc, 50, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("15 "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("31"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("32"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("33"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("34"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("35"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("36"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("37"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("38"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("39"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("40"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("41"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("42"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("43"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("44"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("45"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("46"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("47"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("48"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("49"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("50"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("51"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("52"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("53"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("54"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("55"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("56"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("57"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("58"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("59"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("60"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("61"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("62"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("63"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("64"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("65"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("66"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("67"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("68"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("69"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("70"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("71"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("72"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("73"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("74"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("75"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("76"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("77"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("78"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("79"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxagemogc), _("80"));

  radiobuttonhommemogc = gtk_radio_button_new_with_mnemonic (NULL, _("Homme"));
  gtk_widget_show (radiobuttonhommemogc);
  gtk_fixed_put (GTK_FIXED (fixed6), radiobuttonhommemogc, 208, 256);
  gtk_widget_set_size_request (radiobuttonhommemogc, 80, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonhommemogc), radiobuttonfemmemogc_group);
  radiobuttonfemmemogc_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonhommemogc));

  label46sat = gtk_label_new (_("Satisfaction"));
  gtk_widget_show (label46sat);
  gtk_fixed_put (GTK_FIXED (fixed6), label46sat, 40, 368);
  gtk_widget_set_size_request (label46sat, 96, 24);

  buttonmodifiermogc = gtk_button_new ();
  gtk_widget_show (buttonmodifiermogc);
  gtk_fixed_put (GTK_FIXED (fixed6), buttonmodifiermogc, 224, 408);
  gtk_widget_set_size_request (buttonmodifiermogc, 88, 32);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonmodifiermogc), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_(" Modifier"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox18), label43, FALSE, FALSE, 0);

  checkbutton3 = gtk_check_button_new_with_mnemonic (_("oui"));
  gtk_widget_show (checkbutton3);
  gtk_fixed_put (GTK_FIXED (fixed6), checkbutton3, 136, 368);
  gtk_widget_set_size_request (checkbutton3, 118, 24);

  g_signal_connect ((gpointer) buttonaffichermogc, "clicked",
                    G_CALLBACK (on_buttonaffichermogc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourmogc, "clicked",
                    G_CALLBACK (on_buttonretourmogc_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobuttonhommemogc, "toggled",
                    G_CALLBACK (on_radiobuttonhommemogc_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifiermogc, "clicked",
                    G_CALLBACK (on_buttonmodifiermogc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowmodifiergc, windowmodifiergc, "windowmodifiergc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, entryidmogc, "entryidmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, entryprenommogc, "entryprenommogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, entrynommogc, "entrynommogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, entrymdpmogc, "entrymdpmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, entrynumtelmogc, "entrynumtelmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, spinbuttondijmogc, "spinbuttondijmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, spinbuttondimmogc, "spinbuttondimmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, spinbuttondiamogc, "spinbuttondiamogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, labelidmogc, "labelidmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, labelprenommogc, "labelprenommogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, labelnommogc, "labelnommogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, labelmdpmogc, "labelmdpmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, labelsexemogc, "labelsexemogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, labelagemogc, "labelagemogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, labeldimogc, "labeldimogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, buttonaffichermogc, "buttonaffichermogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, image17, "image17");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, label41, "label41");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, buttonretourmogc, "buttonretourmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, image16, "image16");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, label40, "label40");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, radiobuttonfemmemogc, "radiobuttonfemmemogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, labelnumtelmogc, "labelnumtelmogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, comboboxagemogc, "comboboxagemogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, radiobuttonhommemogc, "radiobuttonhommemogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, label46sat, "label46sat");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, buttonmodifiermogc, "buttonmodifiermogc");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, image18, "image18");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, label43, "label43");
  GLADE_HOOKUP_OBJECT (windowmodifiergc, checkbutton3, "checkbutton3");

  return windowmodifiergc;
}

