/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_windowmaingc (void);
GtkWidget* create_windowajoutergc (void);
GtkWidget* create_windowsupprimergc (void);
GtkWidget* create_windowaffichergc (void);
GtkWidget* create_windowmodifiergc (void);
